import * as g                           from '../../types/genetics'

export const en_r: g.Ribosome[] = [
    // {
    //     institute   : "en",
    //     code        : "CMSTRIP",
    //     type        : "comic",
	// 	level       : "B1",
	// 	title       : "Commit Strip for Developers",
    //     avatar      : "https://prashantsani.com/spider/content/images/size/w2000/2017/04/commitStrip-Rise-of-the-coders-English-Hardcover.jpg",
    //     source      : "commitstrip.com",
    //     contains    : "∞",
    //     readMode    : "start"
    // },
    {
        institute   : "en",
        code        : "BBCSHSP",
        type        : "audio",
		level       : "B1",
		title       : "Shakespeare Speaks",
        avatar      : "https://www.open.edu/openlearn/sites/www.open.edu.openlearn/files/styles/ole_ng_content_style_featured/public/ole_images/screen-feat.png",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCCHCO",
        type        : "audio",
		level       : "B2",
		title       : "A Christmas Carol",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p07xny96.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCALIC",
        type        : "audio",
		level       : "B2",
		title       : "Alice in Wonder-\nland",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p02kvlvk.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCGVTR",
        type        : "audio",
		level       : "B2",
		title       : "Gulliver's Travels",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p033wm70.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCITBE",
        type        : "audio",
		level       : "B2",
		title       : "The Importance of Being Earnest",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p06t92r9.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCINNM",
        type        : "audio",
		level       : "C1",
		title       : "Jamaica Inn",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p08hqrpl.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "BBCRACE",
        type        : "audio",
		level       : "C1",
		title       : "Race",
        avatar      : "https://ichef.bbci.co.uk/images/ic/320x180/p0252gs9.jpg",
        source      : "bbc.co.uk",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOA1",
        type        : "video",
		level       : "A1",
		title       : "Storyline Online\nA1",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOA2",
        type        : "video",
		level       : "A2",
		title       : "Storyline Online\nA2",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOB1",
        type        : "video",
		level       : "B1",
		title       : "Storyline Online\nB1",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "STRYOB2",
        type        : "video",
		level       : "B2",
		title       : "Storyline Online\nB2",
        avatar      : "https://i0.wp.com/speechisbeautiful.com/wp-content/uploads/2016/03/storylineonline.png",
        source      : "storylineonline.net",
        contains    : null,
        readMode    : "end",
        private     : false,
    },
    {
        institute   : "en",
        code        : "INTSDAY",
        type        : "audio",
		level       : "C1",
		title       : "Interesting\nThing of\nthe Day",
        avatar      : "https://www.kickassfacts.com/wp-content/uploads/2017/01/fact-of-the-day.jpg",
        source      : "itotd.com",
        contains    : null,
        readMode    : "start",
        private     : true,
    },
    {
        institute   : "en",
        code        : "VOASTRY",
        type        : "audio",
		level       : "B1",
		title       : "American Stories",
        avatar      : "https://cdn.pixabay.com/photo/2019/05/14/21/50/storytelling-4203628__340.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAPRMS",
        type        : "audio",
		level       : "B1",
		title       : "A Princess of Mars",
        avatar      : "https://4.bp.blogspot.com/-198vAkdju2E/V9hcNtX3l1I/AAAAAAABaI4/BtQnCf2rgrAhhgUh7qs5Si-V9_kOkkzGACLcB/w1200-h630-p-k-no-nu/A%2BPrincess%2Bof%2BMars%2Bby%2BMatt%2BTaylor.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOABENC",
        type        : "audio",
		level       : "B1",
		title       : "Benito Cereno",
        avatar      : "https://cdn.pixabay.com/photo/2016/10/18/07/30/ship-1749467_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAWISN",
        type        : "audio",
		level       : "B1",
		title       : "William Wilson",
        avatar      : "https://moellerlit.weebly.com/uploads/1/0/2/4/10248653/533359_orig.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAMURM",
        type        : "audio",
		level       : "B1",
		title       : "The Murders in the Rue Morgue",
        avatar      : "https://cdn.pixabay.com/photo/2017/10/10/08/36/halloween-2836379_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOALLWF",
        type        : "audio",
		level       : "B1",
		title       : "The Law of Life",
        avatar      : "https://cdn.pixabay.com/photo/2018/08/13/15/37/wolf-3603190_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAFHUS",
        type        : "audio",
		level       : "B1",
		title       : "The Fall of the House of Usher",
        avatar      : "https://i.ytimg.com/vi/J3wo6ISCWQU/maxresdefault.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOADLNS",
        type        : "audio",
		level       : "B1",
		title       : "The Diamond Lens",
        avatar      : "https://cdn.pixabay.com/photo/2018/03/19/17/38/desktop-3240606_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOABRYS",
        type        : "audio",
		level       : "B1",
		title       : "The Bride Comes to Yellow Sky",
        avatar      : "https://cdn.pixabay.com/photo/2017/11/21/09/00/model-2967646_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOABLUH",
        type        : "audio",
		level       : "B1",
		title       : "The Blue Hotel",
        avatar      : "https://cdn.pixabay.com/photo/2019/07/31/17/21/pool-4375669_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAHRCR",
        type        : "audio",
		level       : "B1",
		title       : "Hearts and Crosses",
        avatar      : "https://cdn.pixabay.com/photo/2019/09/12/16/01/cross-4471977_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOALVLF",
        type        : "audio",
		level       : "B1",
		title       : "Love of Life",
        avatar      : "https://cdn.pixabay.com/photo/2018/10/22/09/09/jaguar-3764824_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAPACA",
        type        : "audio",
		level       : "B1",
		title       : "Paul's Case",
        avatar      : "https://cdn.pixabay.com/photo/2016/03/09/09/37/railway-1245906_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOARAPG",
        type        : "audio",
		level       : "B1",
		title       : "Rappaccini\n’s\nDaughter",
        avatar      : "https://images.squarespace-cdn.com/content/586c9aa4bebafbc74759b4d2/1484878357680-PXLNN6BQMSCVOTSI9VE9/key+scene+2+re.png?format=1000w&content-type=image%2Fpng",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "VOAANA1",
        type        : "video",
		level       : "A1",
		title       : "Let's Learn English\nA1",
        avatar      : "https://cdn.pixabay.com/photo/2020/02/05/08/59/painting-4820485_960_720.jpg",
        source      : "learningenglish.voanews.com",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "GMZPRVB",
        type        : "plain",
		level       : "B1",
		title       : "Sayings\n&\nProverbs",
        avatar      : "https://cdn.pixabay.com/photo/2016/06/10/21/58/collection-1448976_960_720.jpg",
        source      : "https://www.grammar.zone/",
        contains    : null,
        readMode    : "start",
        private     : false,
    },
    {
        institute   : "en",
        code        : "GCF35CH",
        type        : "plain",
		level       : "A2",
		title       : "35 Ancient Chinese Proverbs & Quotes",
        avatar      : "https://cdn.pixabay.com/photo/2019/12/20/09/02/bamboo-digital-paper-4708017_960_720.jpg",
        source      : "https://www.geckoandfly.com/19031/ancient-chinese-proverbs-quotes-love-life-wisdom-knowledge-success/",
        contains    : null,
        readMode    : "start",
        private     : false,
    },



    {
        institute   : "en",
        code        : "EATGOUT",
        type        : "audio",
		level       : "A2",
		title       : "Eating\nOut",
        avatar      : "https://image.freepik.com/free-vector/people-eating-out-public-place-sitting-outdoors_82574-11144.jpg",
        source      : "LingQ",
        contains    : null,
        readMode    : "start",
        private     : true,
    },

]