import * as g                           from '../../types/genetics'

export const ABC: g.snapMargin = [] as any;
export const MDL: g.OrganelleType[] = [ "dAudio", "rawText" ];
export const DNA: g.gene[] = [
	{
		"title"		: "In a pickle",
		"text"		: "Narrator: It was a chilly November evening. William Shakespeare's play The Tempest, full of music, magic and monsters, is being performed for the first time. King James I and the Queen are having dinner while they watch.\nKing James: I do like a good play… mmm… and this meat is delicious - bring me more of that pickle… Mmmm… I love a bit of pickle with my dinner… and a nice glass of wine…\nQueen: Don't you think you've had enough wine, dear?\nKing James: Oh do be quiet dear: I can't hear the actors. Now, Mr Shakespeare, is that a King I see on the stage?\nWill: Your Majesty, that is King Alonso of Naples. He is lost on a magical island.\nKing James: And who is this fellow in the jester's costume?\nWill: Your Majesty, that is Trinculo. He drinks a lot, and plans to murder people.\nKing James: A drunken jester? Murder? No good will come of it… does the King know about this?\nWill: Yes, your Majesty. Now, the King is going to find Trinculo - in a drunken mess. Your Majesty might care to listen…\nKing James 1: Ooh yes, yes, I want to hear this, be quiet everybody.\nAlonso: How camest thou in this pickle?\nRobert Harley as Trinculo: I have been in such a pickle since I saw you last that, I fear me, will never out of my bones: I shall not fear fly-blowing.\nKing James 1: Hahaha! He's in a pickle! I like it, Will, very good, very good!\nNarrator: We'll leave them there for now. Pickles are a very messy food, made from fruit and vegetables, crushed and preserved in vinegar and spices - sometimes with alcohol too. When Trinculo says he is in a pickle, he's probably saying that he is very drunk - but he's also got himself into a mess - a very difficult situation. Nowadays, when someone has drunk a lot of alcohol, they can say: I'm pickled - and when they've got problems, they can say: I'm in a pickle. Take The Hunger Games actor Liam Hemsworth, who said:\nClip 1: Most of the time if I'm in a pickle I'll call one of my brothers. They've usually got somewhat uplifting advice.\nClip 2: Ooh, you're in a pickle with those bags aren't you? Let me help.\nKing James I: Now Mr Shakespeare, sit down and eat with us. Have some cold meat!\nServant: Anything with that?\nWill: Hmmm… To pickle, or not to pickle: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03mwdn4.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_in_a_pickle_download.mp3"
	},
	{
		"title"		: "As dead as a doornail",
		"text"		: "Narrator: It was a cold morning. William Shakespeare is in the theatre, working on Henry VI part II, whilst his actor friend Thomas Swann is mending a broken door.\nWill: Thomas! Can you stop that banging? I'm trying to write here!\nThomas: Will, this door needs fixing properly. I have to hit this doornail hard… there. That will never come out.\nWill: What's that about a doornail? Hmmm… you've just given me an idea… dead as a doornail… dead as a doornail!\nThomas: Who's dead?! Will?\nWill: Thomas, I have the perfect line for your character… Jack Cade, the rebel leader, strong and proud. But in this scene, he's on the run, hiding from his enemies. He hasn't eaten anything for five days, except herbs… even grass… he's weak… alone… and suddenly, six of his enemies find him.\nThomas: So he's in danger…\nWill: Yes, but he doesn't show any fear: in fact, he threatens to kill all of them dead as a doornail. Come Thomas, let's read your lines. Look on me well: I have eat no meat…\nThomas as Jack Cade: Look on me well: I have eat no meat these five days; yet come thou and thy five men, and if I do not leave you all as dead as a doornail, I pray God I may never eat grass more.\nWill: You have it! Well done Thomas: there's another classic Shakespeare line.\nThomas: I don't know how you do it, Will.\nNarrator: We'll leave them there for now. The phrase as dead as a doornail was in common use in Shakespeare's day. It means the same today as it did back then: Dead. Very dead. Totally dead. It's a very well-known English expression - for example, novelist Charles Dickens used it to describe the character Marley in A Christmas Carol:\nClip 1: Old Marley was as dead as a doornail.\nNarrator: These days we can use it for electrical gadgets that aren't working.\nClip 2: Oh no - I forgot to charge my phone. It's as dead as a doornail.\nWill: Right! All that writing has made me thirsty. Let us go to the Duck and Whistle. Come on Thomas, close the door behind you… Hmmm… perhaps you should put another couple of nails in that door before we go, Thomas?\nThomas: Ahh… To nail, or not to nail: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03g77bn.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_as_dead_as_a_doornail_download.mp3"
	},
	{
		"title"		: "I'll send him packing",
		"text"		: "Narrator: It's early morning at the Globe Theatre. William Shakespeare and his actors are rehearsing Henry IV Part 1. In this scene, it's late at night, and young Prince Hal, played by Robert Harley, and his friend Falstaff – that's Thomas Swann – are in the pub. But… the King's messenger has just arrived.\nThomas Swann as Falstaff: … Shall I give him his answer?\nRobert Harley as Prince Hal: Prithee do, Jack.\nThomas Swann as Falstaff: Faith and I'll send him packaged…\nWill: Stoooppppp!!! Thomas, Thomas, it's packing… I'll send him packing… Not packaged. You're not putting him in a box or a parcel. Remember: you want the King's messenger to go away!\nThomas Swann: Sorry, Will… I'm not my best today…\nActor 1: One too many beers last night, eh Thomas?!\nActor 2: He thinks he's Falstaff for real!\nWill: Thomas. Listen to me. Falstaff and Prince Hal are having a great time. That's why Hal doesn't want to see the messenger.\nRobert Harley: Will…\nWill: What is it, Robert?!\nRobert Harley: I do like the messenger's name: Gravity. Gravity! A serious man who doesn't like to have fun. Not like Falstaff. He's…\nActor 1: Old!\nActor 2: …and fat!\nActor 1: He's always telling jokes…\nActor 2: He's never got any money!\nThomas Swann: That last bit's true enough, Will.\nWill: Now, now Thomas – you're perfect for this part. The audience are going to love you! Let's go again, from: What doth Gravity do out of his bed at midnight?\nThomas Swann as Falstaff: What doth Gravity do out of his bed at midnight? Shall I give him his answer?\nRobert Harley as Prince Hal: Prithee do, Jack.\nThomas Swann as Falstaff: Faith, and I'll send him packing!\nWill: Bravo! Let's take a break.\nNarrator: We'll leave them there for now. Falstaff is one of Shakespeare's most popular characters. He drinks, steals and runs away from danger, but Shakespeare’s audiences loved his comic genius and sense of fun. In Henry IV, Prince Hal prefers the company of Falstaff – and his criminal friends – to noblemen. Shakespeare’s phrase I'll send him packing has the same meaning today: I really don't want this person around me, so I'll send them away. It's also used in sport, to talk about beating an opponent. Take Gwyn Jones, former captain of the Welsh rugby team, who said before a match:\nClip 1: This is our chance to do it and we should send them packing with their tails between their legs.\nClip 2: I've no patience when people try to sell me things at the door. I usually send them packing.\nWill: Let's try it once more.\nActor 1: Come on Thomas!\nActor 2: You can do it!\nThomas Swann: Will you all shush?!\nActors 1 & 2: To shush or not to shush, that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03gv0s2.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_send_him_packing_download.mp3"
	},
	{
		"title"		: "All that glisters is not gold",
		"text"		: "Narrator: It was a sunny afternoon. William Shakespeare is working on his play The Merchant of Venice. His daughter comes to see him.\nDaughter: Father, look at my new ring! Isn't it lovely, gold and shiny…\nWill: Dear daughter, it is very beautiful. Where did you get such a pretty thing?\nDaughter: From the market. It was much cheaper than the gold merchant!\nWill: Is it real gold?\nDaughter: Yes, of course!\nWill: So, my dear daughter, why is your finger green?\nDaughter: Oohhhh!\nWill: My dear daughter, you have a lot to learn… sit with me while I work. The Merchant of Venice. The Prince of Morocco wants to marry the beautiful Portia. But first, he must choose between three boxes: one made of gold, the second of silver, and the third, of cheap lead. Only one of the boxes contains a picture of Portia, and if the Prince chooses the wrong one, he cannot marry her. So, dear daughter, which box does he choose?\nDaughter: The gold box! Is it real gold?\nWill: He chooses the gold box indeed, and indeed it is real gold. The Prince believes that only the most beautiful box can hold the painting of the beautiful Portia. But in fact, it holds not a picture, but a scroll with these words: All that glisters is not gold…\nRobert Harley as The Prince of Morocco: All that glisters is not gold;: Often have you heard that told:: Many a man his life hath sold: But my outside to behold:\nDaughter: He thought that because the box is beautiful on the outside, something beautiful must be inside… he was wrong.\nNarrator: We'll leave them there for now. The Merchant of Venice is a play about money, money, money, and the phrase all that glisters is not gold warns us not to be fooled by people or things that look good - because they might not be as good as they look on the surface! In modern English, the word glisters is often changed to glistens or glitters. \nClip 1: Well that car looks fantastic, but all that glitters is not gold. Check the engine before you buy it.\nDaughter: Oh father, will you buy me a real gold ring? Pleeeeeaase?\nWill: Hmmm… to buy, or not to buy: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03f264d.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_all_that_glisters_download.mp3"
	},
	{
		"title"		: "Strange bedfellows",
		"text"		: "Narrator: It's late in the evening. William Shakespeare is visiting his actor friend Robert Harley.\nRobert: Will! Just one moment… I have to rescue the cat. It likes to sleep with the chickens and it gets locked in the henhouse… come on kitty…\nWill: The cat sleeps with the chickens? That's unusual.\nRobert Harley: It's strange, but they seem quite happy together. So, Will, I've read your new play The Tempest and I'm very excited about all the magic, the music and the monsters, and my character, Trinculo, the lost traveller: it's a wonderful part. His meeting with Caliban: it's very interesting.\nWill: Ah, yes, Caliban. Neither man nor fish – a weird sort of creature.\nRobert Harley: You put them both in a storm…\nWill: Yes: it's an old trick but it's a good way to bring them together. Trinculo needs shelter and the strange, well, almost monstrous Caliban is wearing a gaberdine: a large coat, big enough for both of them. Trinculo gets under it, safe and warm from the storm.\nRobert Harley: But Trinculo isn't happy…\nWill: He's feeling very miserable. He actually says: Alas, the storm is come again! My best way…\nRobert Harley as Trinculo: Alas, the storm is come again! My best way is to creep under his gaberdine; there is no other shelter hereabouts: misery acquaints a man with strange bedfellows.\nWill: Ohh, I do like that line: Misery acquaints a man with strange bed-fellows. When times are hard, people do things they don't normally do…\nNarrator: We'll leave them there for now. Shakespeare lived in a time of discovery – strange new lands and creatures, so the mysterious island of The Tempest appealed to Shakespeare's audience as both exciting and scary. These days, the phrase strange bedfellows describes two people or groups that are connected in a particular activity, even though they are very different and are not usually seen together. It's often used for political alliances. For example, a July 2015 report from US broadcaster Fox News described Israel and Hamas as strange bedfellows when they both wanted to stop the growth of so-called Islamic State in Gaza. The headline was:\nClip 1: Israel, Hamas strange bedfellows when it comes to reining in ISIS in Gaza.\nNarrator: Strange bedfellows is useful for all sorts of unlikely partnerships.\nClip 2: You think Miley Cyrus and Michael Bublé should write a song together? Well, they'd be strange bedfellows… but it might just work.\nRobert Harley: Now Will, it's getting late and there's a storm coming. You must stay with us tonight. You can sleep in the henhouse – or you can share a bed with the Harley family.\nWill: Hmmm… To bed or not to bed: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03hxy1c.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_strange_bedfellows_download.mp3"
	},
	{
		"title"		: "Though this be madness, yet there is method in't",
		"text"		: "Narrator: It was late in the evening. Actors Thomas Swann and Robert Harley are having a drink in the Duck and Whistle after a rehearsal of William Shakespeare's Hamlet.\nBarmaid: Here you are Mr Robert, Mr Thomas: two more ales.\nThomas Swann: Now Robert, the big question in Hamlet for me is – oh, hello, Will.\nWill: Good evening Thomas, Robert…\nThomas Swann: Will. About your character Hamlet. Is he really mad?\nBarmaid: Good evening Mr Will – oohh, he's a tricky fellow that Hamlet. The way I see it, Mr Thomas, is, he's not really mad. He wants to find out who killed his father, and he thinks if he pretends to be mad, the killer will stop hiding the truth from him. Isn't that right Mr Will?\nWill: Indeed it is, Bess.\nBarmaid: Hamlet says all sorts of crazy things about maggots in dogs and crabs walking backwards… no wonder everyone thinks he's mad. I'm a big fan of yours, Mr Will.\nWill: Thank you, Bess.\nRobert Harley: But if Polonius thinks Hamlet is mad, why does he say: Though this be madness, yet there is method in't?\nBarmaid: Well I think, Mr Robert, that's partly because some of the crazy things that Hamlet says actually make sense. That's why Polonius thinks Hamlet is somehow in control of his madness, because Hamlet says: For yourself, sir, should be as old as I am…\nRobert Harley as Hamlet: For yourself, sir, should be as old as I am, if like a crab you could go backward.\nThomas Swann as Polonius: Though this be madness, yet there is method in't.\nBarmaid: That Polonius is an old fool – he doesn’t know Hamlet’s insulting him. I've seen all your plays, Mr Will.\nWill: I know you have, dear Bess.\nNarrator: We'll leave them there for now. The name Hamlet is very similar to Hamnet, Shakespeare's son, who died at just 11 years old. It's possible that Shakespeare's grief influenced the outpouring of hopelessness and grief in Hamlet's speeches that follow the death of his father, the King. The modern version of the phrase Though this be madness, yet there is method in't is simply: there's method in his madness – or her madness, or my madness – and it means: there's a sensible reason for something that seems crazy. Take snooker champion Ronnie O'Sullivan, talking about how his father introduced him to snooker. He said:\nClip 1: My dad's method in his madness was to try every sport and then observe what I liked. I played football, tennis, golf, cricket – but I loved my snooker.\nClip 2: My mum's desk is covered in papers. There's method in her madness, though. She knows where everything is!\nThomas Swann: So Hamlet isn't mad – he's just pretending.\nShakespeare: That's right – exactly.\nRobert Harley: This is one crazy plot…\nBarmaid: Mr Will knows what he's doing, believe me.\nRobert Harley: Hmm… To be-lieve or not to be-lieve:\nThomas Swann: …that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03j421w.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_though_this_be_madness_download.mp3"
	},
	{
		"title"		: "Wild-goose chase",
		"text"		: "Narrator: It was early in the evening. William Shakespeare is at home. He's expecting a visit from his actor friend Robert Harley.\nRobert Harley: Good evening, Mr Shakespeare.\nWill: Welcome, welcome Robert! Come in.\nDaughter: Good evening Mister Harley…\nRobert Harley: Miss Shakespeare… I'm sorry I’m late - I was out horse riding. It was wonderful - so fast, so exciting!\nWill: Ahhh, the wild-goose chase! Take care when you race that way young Robert, we don't want to spoil those good looks of yours…\nDaughter: Why is it called a wild-goose chase? It's a horse race! They're not chasing geese!\nWill: Dear daughter, a wild-goose chase is indeed a kind of horse race. The riders have to follow one horse, keeping up with him wherever he goes, just as wild geese follow the leader when they fly.\nDaughter: Ohhh… I expect you kept up with him very well, Robert…!\nWill: Thank you, daughter. Now to the play: Romeo and Juliet. Robert, you are playing Mercutio, Romeo's best friend. In this scene, there is a different kind of wild-goose chase. This chase is all about words and jokes. Mercutio and Romeo are competing with each other: each of them trying to tell the cleverest and funniest jokes.\nRobert: A competition of intelligence, of wits and quick thinking!\nDaughter: Mercutio will win, won't he!? He is handsome - and clever!\nWill: Mercutio is indeed quick-witted, but Romeo is better - much better, and Mercutio knows it - so he gives up this wild-goose chase before it even starts, saying: Nay, if thy wits run the wild-goose chase…\nRobert as Mercutio: Nay, if thy wits run the wild-goose chase, I have done,: for thou hast more of the wild goose in one of: thy wits than, I am sure, I have in my whole five.\nNarrator: We'll leave them there for now. Romeo and Juliet is a play about young love, but it also has lots of fighting, with both weapons and words. Here, Shakespeare compares Romeo and Mercutio's duelling with words to a wild and dangerous horse race, called a wild-goose chase. In modern English, a wild-goose chase isn't about horses, or geese: it describes a situation where you foolishly chase after something that is impossible to get - or doesn't exist at all. Take US writer Bryant McGill, who said:\nClip 1: Endless consumerism sends us on a wild-goose chase for happiness through materialism.\nClip 2: We looked for the restaurant for hours, but it was a wild-goose chase: turned out that it closed down years ago!\nRobert: So, no wild-goose chase for Mercutio.\nDaughter: You could chase me, though Robert…\nRobert: Oh dear… to chase, or not to chase: that really isn't a question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03krrw9.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_wild_goose_chase_download.mp3"
	},
	{
		"title"		: "What's done is done",
		"text"		: "Narrator: It was early in the evening. William Shakespeare is at home. He's expecting a visit from his actor friend Robert Harley.\nRobert Harley: Good evening, Mr Shakespeare.\nWill: Welcome, welcome Robert! Come in.\nDaughter: Good evening Mister Harley…\nRobert Harley: Miss Shakespeare… I'm sorry I’m late - I was out horse riding. It was wonderful - so fast, so exciting!\nWill: Ahhh, the wild-goose chase! Take care when you race that way young Robert, we don't want to spoil those good looks of yours…\nDaughter: Why is it called a wild-goose chase? It's a horse race! They're not chasing geese!\nWill: Dear daughter, a wild-goose chase is indeed a kind of horse race. The riders have to follow one horse, keeping up with him wherever he goes, just as wild geese follow the leader when they fly.\nDaughter: Ohhh… I expect you kept up with him very well, Robert…!\nWill: Thank you, daughter. Now to the play: Romeo and Juliet. Robert, you are playing Mercutio, Romeo's best friend. In this scene, there is a different kind of wild-goose chase. This chase is all about words and jokes. Mercutio and Romeo are competing with each other: each of them trying to tell the cleverest and funniest jokes.\nRobert: A competition of intelligence, of wits and quick thinking!\nDaughter: Mercutio will win, won't he!? He is handsome - and clever!\nWill: Mercutio is indeed quick-witted, but Romeo is better - much better, and Mercutio knows it - so he gives up this wild-goose chase before it even starts, saying: Nay, if thy wits run the wild-goose chase…\nRobert as Mercutio: Nay, if thy wits run the wild-goose chase, I have done,: for thou hast more of the wild goose in one of: thy wits than, I am sure, I have in my whole five.\nNarrator: We'll leave them there for now. Romeo and Juliet is a play about young love, but it also has lots of fighting, with both weapons and words. Here, Shakespeare compares Romeo and Mercutio's duelling with words to a wild and dangerous horse race, called a wild-goose chase. In modern English, a wild-goose chase isn't about horses, or geese: it describes a situation where you foolishly chase after something that is impossible to get - or doesn't exist at all. Take US writer Bryant McGill, who said:\nClip 1: Endless consumerism sends us on a wild-goose chase for happiness through materialism.\nClip 2: We looked for the restaurant for hours, but it was a wild-goose chase: turned out that it closed down years ago!\nRobert: So, no wild-goose chase for Mercutio.\nDaughter: You could chase me, though Robert…\nRobert: Oh dear… to chase, or not to chase: that really isn't a question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03kftxg.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_whats_done_is_done_download.mp3"
	},
	{
		"title"		: "The world's mine oyster",
		"text"		: "Narrator: The year is 1599. William Shakespeare is at the palace of Queen Elizabeth I of England. The Queen has ordered Shakespeare to write another play.\nQueen Elizabeth I: Mr Shakespeare. Tell me about my new play.\nWill: Your Majesty, The Merry Wives of Windsor is a comedy, in which Sir John Falstaff tries to trick two married ladies into giving him money behind their husbands' backs.\nQueen Elizabeth I: Falstaff! Hahaha! He is such a wicked man... that's why I like him. Or maybe he reminds me of our dear friend Sir Walter Raleigh, who brings me treasure from around the world. Look at my pearls, taken from a Spanish ship by Raleigh and brought to me as a gift.\nWill: They are beautiful, your Majesty. Whoever could guess that such a creature, deep in the ocean, could contain the most beautiful, precious treasure: a pearl?!\nQueen Elizabeth I: Yessss... to Raleigh, the whole world is an oyster... full of treasure, ready for the taking. By force if need be... he is not afraid to use the sword to bring me my treasure.\nWill: Mr Raleigh is your loyal servant, your Majesty, as am I.\nQueen Elizabeth I: To Falstaff. What of his trickery?\nWill: Your Majesty, while Falstaff is trying to get money from the wives, his friend Pistol is trying to get money out of him!\nQueen Elizabeth I: Hahaha! Does he get it?\nWill: Falstaff tells Pistol he won't give him a penny. Pistol becomes angry and says he'll get his sword and open up Falstaff's money bag - or any money bag he can find - like he's opening an oyster with a knife! It goes like this. I will not lend thee a penny...\nThomas Swann as Falstaff: I will not lend thee a penny.\nRobert Harley as Pistol: Why, then the world's mine oyster.: Which I with sword will open. \nQueen Elizabeth I: The world's mine oyster. It's full of money and treasure. Quite right, Mr Shakespeare, quite right.\nNarrator: We'll leave them there for now. The Merry Wives of Windsor was Shakespeare's only comedy to be set entirely in England, and it's considered to be his most realistic portrayal of the daily lives of ordinary people. Think of it as the original 'Real Housewives'. In Shakespeare's play, the phrase the world's mine oyster was used as a threat - but today, it has become the world's my oyster - or your oyster - and it describes situations that contain wonderful opportunities. Take US entrepreneur Chris Gardner, who wrote in his autobiography The Pursuit of Happyness:\nClip 1: The world is your oyster. It's up to you to find the pearls.\nNarrator: It can describe the opportunities that open up when you take risks, have money or learn new skills.\nClip 2: If you learn foreign languages, the world's your oyster.\nQueen Elizabeth I: Mr Shakespeare, I am pleased. Your actors will perform this play for me.\nWill: To perform, or not to perform: I'll just do what she tells me.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03ks7q5.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_the_worlds_mine_oyster_download.mp3"
	},
	{
		"title"		: "A tower of strength",
		"text"		: "Narrator: It was a dark and stormy night. Thomas Swann is in his favourite pub, the Duck and Whistle. He's rehearsing the role of King Richard in Shakespeare's Richard III.\nThomas: The King's name is a tower of strength... Hmmm. I could play it quietly: The King's name is a tower of strength... or angrily: The King's name is a tower of strength...\nBarmaid: Here you go Mr Will, Mr Thomas, two more ales.\nThomas: Will, how should I play this line? What is Richard's motivation here?\nWill: Thomas, Thomas, don't you understand? King Richard is about to go into battle. The opposing army has six or seven thousand men.\nThomas: That's a lot of men!\nWill: Richard is not afraid. He has three times that number of soldiers.\nThomas: Twenty thousand men - that's a big army!\nWill: Yes, but Richard has something more powerful than even the greatest army. He has his name: King Richard. That name makes him strong; powerful. It makes ordinary people fear and respect him.\nThomas: So the name King Richard is as strong as a tower...\nWill: Exactly. Richard's enemies don't have that.\nThomas: So this line needs strength and confidence.\nWill: Yes. This play is about power - and what people will do to get it. Let us rehearse. I am Norfolk, your general. Six or seven thousand is their utmost power.\nThomas Swann as Richard III: Why, our battalion trebles that account. Besides, the King's name is a tower of strength\nWhich they upon the adverse party want.\nWill: You have it! Well done! I'll drink to that. Another jug of ale! \nBarmaid: Here you are, sir.\nNarrator: We'll leave them there for now. In Richard III, or as I like to call it, the Mafia play, King Richard murdered everyone that stood between him and the absolute power that he wanted, including the Prince of Wales, his brother Clarence, Misters Rivers, Vaughn and Grey, Lord Hastings, King Edward IV's two young sons - and his own wife! Of course, these days, you don't have to kill your family to be described as a tower of strength - you just have to be strong, reliable, trustworthy, dependable and good in a crisis. Like footballer David Beckham, who said:\nClip 1: Alex Ferguson was like a father to me. He was a tower of strength.\nClip 2: My husband was a tower of strength when I had that operation - he really looked after me well.\nBarmaid: Mr Will, a message from your wife. She says if you're not home in five minutes, don't bother coming home ever again.\nThomas: The old ball and chain at it again, eh? Come on Will, have another beer!\nWill: Hmmm... To beer, or not to beer: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03ls7xq.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_a_tower_of_strength_download.mp3"
	},
	{
		"title"		: "Spotless reputation",
		"text"		: "Narrator: It was a spring morning in 1601. William Shakespeare is visiting Queen Elizabeth I of England. She's not very happy today...\nQueen Elizabeth I: I will not allow my enemies to live. Tomorrow that ill-faced, murderous coward the Earl of Essex will die, and the people will know that I commanded it.\nWill: Very good, your Majesty.\nQueen Elizabeth I: Your players will perform Richard II for me tomorrow.\nWill: A great honour, your Majesty.\nQueen Elizabeth I: Even though they performed that same play for the filthy, crooked Earl of Essex while he was planning to kill me…\nWill: Your Majesty…\nQueen Elizabeth I: I really ought to punish you and your players for that, Shakespeare – I should cut off all your heads, or at least imprison you in the Tower…\nWill: Your Majesty…\nQueen Elizabeth I: Lucky for you that I am a merciful Queen – but I am not weak. I will not allow anyone to speak badly of my character or my actions. I am Queen of England and my reputation is everything. My enemies must fear and respect me and the people must love me. Gossips must be silenced and traitors must be punished. Do you not agree?\nWill: Your Majesty is the wisest of queens. A good reputation is everything. Indeed, in my play, Richard II, Thomas Mowbray says: \"My dear dear lord, The purest treasure…\nThomas Mowbray: My dear dear lord,: The purest treasure mortal times afford: Is spotless reputation\nQueen Elizabeth I: Well said, Shakespeare – a spotless reputation is truly the most important and precious thing in any life. You may go.\nWill: Your Majesty…\nNarrator: We'll leave them there for now. In Shakespeare's day, your reputation – the things other people believed and said about your character and actions – was very important. In fact, William Shakespeare's own reputation as a writer was so good that during his lifetime, several dishonest publishers published other, lesser writers' work, pretending that it was Shakespeare's. These days, the phrase spotless reputation describes a person or organisation that has a good, clean character and behaves decently and honestly. Take news website Scottish Herald, discussing the 2015 Volkswagen emissions data falsification scandal. It said:\nClip 1: Analysts have also asked whether the revelations will cause irreversible damage to Volkswagen's previously spotless reputation.\nClip 2: Another athlete caught taking drugs? I'm surprised at this one though – she always had a spotless reputation.\nWill: Robert, Thomas, give me some ale… we're doing Richard II, tomorrow. And it'd better be good, or it could be the Tower.\nRobert Harley & Thomas Swann: Oh dear. Oh no. To the tower, or not to the tower: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03lzq6n.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_spotless_reputation_download.mp3"
	},
	{
		"title"		: "The green-eyed monster",
		"text"		: "Narrator: It was late afternoon. William Shakespeare has just arrived at his favourite pub, The Duck and Whistle. His actor friend Thomas Swann is already there.\nBarmaid: Mr Will. Can you do something about that Mr Thomas? He's been drinking and shouting all afternoon. If you can't shut him up, I'm going to throw him out.\nThomas Swann: I'm a wonderful husband. I give the woman everything and this is how she treats me!\nBarmaid: Be quiet, you silly old fool. See, Mr Will? His head's full of jealous nonsense about his wife. That Robert Harley said he saw her talking to Henry Darcy, and now he's all in a rage…\nThomas: That filthy toad… I'll burn his house down… and when I get my hands on her…\nWill: Oh dear. The green-eyed monster attacks again!\nBarmaid: Hmm. Jealousy: the green-eyed monster. You're right Mr Will, jealousy is a monster: it gets inside people, eats them up. Makes them think the worst, like Mr Thomas here, makes them say and do terrible things.\nWill: The green-eyed monster. It's rather clever, isn’t it Bess? It's in my play, Othello. The evil Iago warns his friend, Othello, about the dangers of jealousy. He says: Beware, my lord, of jealousy…\nRobert Harley as Iago: Beware, my lord, of jealousy;: It is the green-ey'd monster, which doth mock: The meat it feeds on.\nBarmaid: Beware the green-eyed monster… that's good advice!\nWill: It is good advice indeed, but Iago's true plan is to make Othello believe that Desdemona, his wife, is cheating on him.\nBarmaid: And is she?\nWill: No, but Iago knows jealousy makes people do crazy things, and his plan works. Othello murders Desdemona!\nBarmaid: That's terrible. Poor Desdemona! We'd better keep an eye on that Mr Thomas!\nNarrator: We'll leave them there for now. In Shakespeare's day, the man was the head of the household, and an unfaithful wife was a great dishonour. The phrase the green-eyed monster is still used today to describe the dangers of uncontrolled jealousy in relationships. For example, Irish pop singer Ronan Keating said of his marriage:\nClip 1: The green-eyed monster rears its ugly head and brings out all my insecurities. I don't like it if Yvonne is out without me. I just can’t help it.\nClip 2: I thought I'd got over my ex, but when I saw him with his new girlfriend, the green-eyed monster got me.\nWill: And now I must go home: Mrs Shakespeare feels that I've been spending rather too much time in the pub. Come on, Thomas…\nBarmaid: Ooooh - it sounds like Mrs S has got the green-eyed monster too!\nThomas Swann: Come on, Will! Stay for another beer!\nWill: Hmmm… To stay, or not to stay: that's a tricky question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03mt0gm.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_the_green_eyed_monster_download.mp3"
	},
	{
		"title"		: "Forever and a day",
		"text"		: "Narrator: It was a rainy day in July. William Shakespeare and his actor friend Robert Harley are rehearsing his comedy The Taming of the Shrew. Will's daughter is watching the rehearsal.\nRobert Harley: Will, I do like your plays when everybody pretends to be somebody else!\nWill: Thank you, Robert. The audience likes it too – that's why it's in the play.\nDaughter: Father, I'm confused… Who is the young man in the teacher's costume?\nWill: That is Lucentio, daughter. He is pretending to be a tutor so that he can be near to Bianca, whom he wants to marry.\nDaughter: So the man wearing Lucentio's clothes isn't the real Lucentio?\nWill: No, he's Lucentio’s servant. He's pretending to be Lucentio so that the real Lucentio can pretend to be a tutor.\nDaughter: Ohhh! That's so romantic, isn't it, Robert?!\nRobert Harley: Well it's very clever Will, but… I can't help thinking that Lucentio should just be a man about it: take the woman to the church and marry her.\nDaughter: Ohhhhh…\nWill: Well, Robert, that is exactly what happens. Lucentio's other servant, Biondello, tells him to stop playing games and to just marry Bianca, because otherwise he risks losing her – not just forever, but forever and a day. Let us rehearse.\nRobert Harley as Biondello: To th' church take the priest, clerk, and some sufficient honest witnesses. If this be not that you look for, I have no more to say, But bid Bianca farewell forever and a day.\nDaughter: Forever and a day – that's a long time to live without your true love…\nNarrator: We'll leave them there for now. Putting characters in disguise was one of Shakespeare's favourite devices: not only because his audiences loved it, but also because it gave him opportunities to explore themes of class, status and love as he swapped the roles of rich and poor, old and young, and male and female characters. The phrase forever and a day means the same as it did in Shakespeare's day: something – either good or bad – will last indefinitely, or for a very, very long time. In his love song Forever and a Day, Lionel Richie sings…\nClip 1: And I'll love you for forever and a day day day day day day day day day day day day,: Forever and a day day day day day day day day…\nClip 2: Oh, look at that queue! We'll be waiting forever and a day. Let's come back tomorrow.\nWill: Now, on with the rehearsal everybody…\nRobert Harley: Speaking of husbands and wives – when are you bringing Mrs Shakespeare to London, Mr Shakespeare?\nWill: Mrs Shakespeare prefers to remain at home in Stratford… and I prefer that too. To bring, or not to bring: that is the question…",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03r4wcr.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_forever_and_a_day_download.mp3"
	},
	{
		"title"		: "Give no words but mum",
		"text"		: "Narrator: It was the 23rd of April. William Shakespeare's daughter and his actor friends Robert Harley and Thomas Swann are at the Duck and Whistle. They're getting ready for a celebration. Bess the barmaid is in charge.\nBess: Now have we got everything? Beer, ale… Where's that Mary Bassett? She's supposed to be bringing the pies…\nMary: Here I am, pies and all! I've brought some lovely meat pies and I've got Mr Will's favourite here: a nice cherry pie.\nAll: Ooohhh lovely, he'll like that, lovely…\nDaughter: Oh, I'm so excited Mary! I love parties! Isn't it wonderful having a party for Father's birthday!\nMary: Now don't you go telling Mr Will before he gets here, Miss Shakespeare, remember: it's a surprise. Like John Hume says in your father's play Henry VI part II: Seal up your lips, and give no words but mum…\nThomas Swann as John Hume: Seal up your lips, and give no words but mum:: The business asketh silent secrecy.\nDaughter: Give no words but mum… I promise, I won't say a word to anyone. Really, I won't!\nNarrator: We'll leave them there for now. The exact date of William Shakespeare's birth is not recorded, but it's generally believed that the most likely date was Sunday the 23rd of April, which, interestingly, was also the date of his death, in 1616, at the age of 52. The phrase Give no words but mum, simply means: don't tell anyone - it's a secret. These days, it's usually simplified to just keep mum. Take Australian news website 9News, writing about Mark Hamill, the Star Wars actor, who spoke of how he had to keep the Star Wars storyline secret. The headline was:\nClip 1: Mark Hamill to keep mum amid Star Wars Skywalker speculation\nNarrator: Another version of the phrase is Mum's the word.\nClip 2: Don't tell anyone you saw me here. Mum's the word!\nMary: Ssshhh everybody, here he comes now!\nAll: Quick, hide, behind the bar, get down, he'll see you…\nWill: Good afternoon Bess, a pint of your finest… Bess? Hello? Where is everyone?!\nAll: Surprise!!!! Happy birthday!!!\nDaughter: Happy birthday father!\nWill: Daughter?! Is all this for me?!\nDaughter: Yes, father, it is!\nThomas Swann: Happy birthday Will!\nWill: Thank you, Thomas.\nMary: Happy birthday, Mr Will. Have some cherry pie.\nBess: Here Mr Will, pint of ale for you.\nWill: Well now! To party, or… no. Let's party!\nAll: Hooray!",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03rtybz.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_give_no_words_but_mum_download.mp3"
	},
	{
		"title"		: "A pound of flesh",
		"text"		: "Narrator: It was late in the evening. William Shakespeare is at the palace of King James I.\nKing James: Mr Shakespeare! Welcome, welcome.\nWill: Your majesty, it is a great honour to perform The Merchant of Venice for you a second time.\nKing James: The Queen and I enjoyed it so much we just had to see it again.\nThe Queen: You fell asleep halfway through dear, that's why you want to see it again.\nKing James: Nonsense. Mr Shakespeare, I particularly enjoyed your character Shylock. But what was all that about a pound of flesh?\nWill: Well, Shylock lent some money to the businessman Antonio. And Antonio promised that if he didn't pay the money back, Shylock could cut a pound of flesh from his body.\nKing James: That's right, that's right. I remember it well now. What did he say? If you repay me not on such a day…\nShylock: If you repay me not on such a day,: In such a place, such sum or sums as are: Express'd in the condition, let the forfeit: Be nominated for an equal pound: Of your fair flesh, to be cut off and taken: In what part of your body pleaseth me.\nNarrator: We'll leave them there for now. A pound of flesh? That's nearly half a kilogram! Modern English speakers use the phrase a pound of flesh when someone says they want justice, but the punishment they're asking for is so severe that it seems more like revenge. In the terrible case of US cinema gunman James Holmes, former prosecutor Bob Grant said:\nClip 1: The district attorney will argue that although the defendant is mentally ill, he is not insane under the law, and society deserves its pound of flesh from him.\nClip 2: I apologised and paid for the repairs after I crashed his car, but it isn't enough for him. He wants his pound of flesh. I think he's going to call the police…\nThe Queen: Mr Shakespeare, please tell the King what happens in the end, just in case he falls asleep again.\nKing James: I did not fall asleep! But yes, do tell me.\nWill: Well, Antonio didn't pay the money back. The court agreed that Shylock could have his pound of flesh, but the court also said that he could not take even a single drop of blood.\nKing James: Aha! So Antonio was saved.\nWill: Yes, your majesty.\nThe Queen: Ooh, the play is starting. Now do stay awake this time, dear…\nKing James: To sleep, or not to sleep: that is the question…",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03s3tmq.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_a_pound_of_flesh_download.mp3"
	},
	{
		"title"		: "A fool's paradise",
		"text"		: "Narrator: It was a sunny August morning. William Shakespeare is at the market.\nStallholder: Get your cherries, lovely ripe cherries! Come over here and get your cherries…\nWill: Ahhh… sweet, ripe cherries! Two pounds, please, Mary.\nStallholder: Here you are Mr Will.\nWill: And how's the family Mary? All well?\nStallholder: Growing up fast, you know how it is… my Janet's a worry though. That Robert Harley says he wants to marry her, but I don't trust him: I think he just wants to have his way with her and what will we do Mr Will if she ends up just 14 years old with a baby and no husband?!\nWill: Now Mary, I'm sure young Robert will do right by Janet. Look at me, didn't I marry my Anne when she was in trouble? And here we are now, still together with three children…\nStallholder: You're not too happy though, are you Mr Will?\nWill: Marriage isn't easy Mary, you know that.\nStallholder: Oh, Mr Will. Last week he was in love with that Rosie from the village and this week it's my Janet's turn. He's promised her clothes, money, ribbons for her hair, and she's so in love with him she believes all of it! I tell you, she's living in a fool's paradise!\nWill: A fool's paradise… hmmm… That might sound good in my play! Romeo and Juliet, the star-cross'd lovers. Romeo says he'll marry Juliet but Juliet's nurse doesn't trust him. She warns him not to make false promises just to get Juliet into bed. Listen Mary, it'll go like this: …let me tell ye, if ye should lead her…\nNurse: let me tell ye, if ye should lead her into: a fool's paradise, as they say, it were a very gross: kind of behaviour,\nStallholder: That's really good Mr Will.\nWill: Thank you, Mary. You can use it if you like…\nNarrator: We'll leave them there for now. In Shakespeare's day, it was legal for girls to marry at the age of 14, although people usually got married when they were older. It was not uncommon for women to already be pregnant when they got married – as was the case with William Shakespeare's own marriage. These days, the phrase a fool's paradise describes any situation that somebody thinks is good, without realising that it won't last – or that it's actually bad. Take this 2015 BBC News headline, written when the value of the single European currency fell to record lows – making it cheap to buy for investors, but not particularly safe:\nClip 1: The euro: Good bet or a fool's paradise?\nClip 2: Jack's work is terrible. He's living in a fool's paradise if he thinks he's getting a pay rise.\nStallholder: Just wait till I catch up with that Mr Robert. If you see him Mr Will, you be sure to tell me.\nWill: Hmmm… to tell, or not to tell: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03sl8jd.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_a_fools_paradise_download.mp3"
	},
	{
		"title"		: "Not budge an inch",
		"text"		: "Narrator: It's evening at the Duck and Whistle. William Shakespeare and his actor friend Thomas Swann are rehearsing the opening scene of Shakespeare's comedy The Taming of the Shrew.\nThomas: I'll answer him by law. I won't budge an inch…\nWill: Just a minute Thomas: Christopher Sly is drunk, but we do need to understand the words!\nThomas: You're criticising my acting, Will. Again.\nWill: Thomas, Thomas. You're a great actor. A wonderful actor. But Thomas, can the audience please actually hear the words I wrote for your character to say…?\nThomas: The audience can see what's happening! I'm in the pub, I'm drunk, there's broken glass everywhere and -\nBess: Thomas Swann! If you've broken one of my glasses, I'll have your guts for garters…\nWill / Thomas: No, no, no!\nThomas: Bess, it's in the play.\nWill: The innkeeper - in the play, Bess - is going to call the police unless Christopher Sly pays for the glasses he broke. But Sly says he doesn't care about the police, he's entitled to be in the pub, and he's not moving.:  : Bess: Oh… well just you be careful. I won't have people breaking glasses in my pub.\nWill: Of course, Bess. Now, Thomas. Please. Speak more clearly.\nThomas: No. I'm an artist, and I have to do it my way.\nWill: Bess, please read the innkeepers lines. I'll be Christopher Sly. Thomas, just listen.\nBess: Alright Mr Will, the innkeeper's lines: I know my remedy. I must go fetch the third-borough.\nWill as Christopher Sly: Third, or fourth, or fifth borough, I'll answer him by law.: I'll not budge an inch, boy. Let him come, and kindly.\nWill: Now please Thomas, do it like that.\nThomas: I will not do it like that.\nBess: He's just like Christopher Sly isn't he Mr Will? He won't budge an inch either.\nNarrator: We'll leave them there for now. Christopher Sly is just one of several stubborn characters in The Taming of the Shrew, Shakespeare's early comedy about the battle of the sexes. The phrase not budge an inch is used these days to describe not only objects that won't move but also people who won't change their minds. Take Simon Walker, the director general of the British Institute of Directors, who said that the British chancellor George Osborne…\nClip 1: …must not budge an inch on the crucial job of deficit reduction.\nClip 2: That stupid dog refused to move. I kept pulling on the lead, but he wouldn't budge an inch.\nThomas: Will, it's my way or –\nWill: Now look here Thomas -\nBess: Now stop arguing you two or I'll knock your heads together. Thomas, do what Mr Will says. It's his play.\nThomas: Grrrr. To budge, or not to budge: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03tm3kq.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_not_budge_an_inch_download.mp3"
	},
	{
		"title"		: "I must be cruel, only to be kind",
		"text"		: "Narrator: It was a windy November day. William Shakespeare is at the palace of King James I. He's having dinner with the King and Queen.\nKing James: Mr Shakespeare, have some more wine. What's this? Water? Where's my wine?!\nThe Queen: Now dear, you know you mustn't drink too much wine. The doctor says it's bad for your health!\nKing James: No wine?! Madam, you are very cruel to me. Don't you agree, Mr Shakespeare?\nWill: Your Majesty, the Queen is being cruel, only to be kind, like my character Hamlet, the Prince of Denmark.\nKing James: Does Hamlet take away the King's wine?\nWill: No, no, your Majesty: Hamlet says cruel and terrible things to his mother, the Queen. He's angry because she married his uncle Claudius, very soon after his father's death. Hamlet suspects that his mother, or his uncle, or both of them, killed his father, so that they could marry each other.\nKing James: Well! No wonder he's saying cruel things. But how is he going to be kind, I wonder? Go on, go on…\nWill: Your Majesty. Hamlet tells his mother that he said these cruel and terrible things to shock her into realising that this marriage is wrong – it's a sin. But he says she can begin to make up for the sin and be a better person if she leaves her new husband. That's why he says 'I must be cruel, only to be kind'.\nRobert Harley as Hamlet: So, again, good night.: I must be cruel, only to be kind:: Thus bad begins and worse remains behind.: One word more, good lady.\nNarrator: We'll leave them there for now. Shakespeare's audiences loved the violence and powerful emotions in his revenge tragedies. But Hamlet is not your typical revenge character. He's a thinker who becomes a man of action. In modern English, Shakespeare's phrase is usually shortened to I must be cruel to be kind. Or just cruel to be kind. People say it when they do something unkind that will actually benefit someone. It's the title of a song in the American movie 10 Things I Hate About You.\nClip 1: Cruel to be kind, it's a very good sign: Cruel to be kind, means that I love you, baby…\nClip 2: I know I upset her when I told her to get a haircut, but it was such a mess: I had to be cruel to be kind.\nKing James: Tell me Mr Shakespeare, does the Queen follow Hamlet's advice?\nWill: I'm afraid not, your Majesty.\nThe Queen: She should have listened to him.\nKing James: Quite right, quite right.\nThe Queen: And you should listen to me dear. No more wine!\nKing James : Hmmm. To listen or not to listen, that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03tt2qg.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_cruel_to_be_kind_download.mp3"
	},
	{
		"title"		: "Wear my heart on my sleeve",
		"text"		: "Narrator: It was a sunny day. William Shakespeare's daughter and Bess the barmaid are at the fair.\nDaughter: Lalalalala…\nBess: You're very happy today aren't you my duck?\nDaughter: Oh Bess, I'm in love.\nBess: You're not still after that Robert Harley are you?\nDaughter: Nooooo! It's Henry Bull. He's wonderful: handsome and brave… and he loves me too… but Bess, father mustn't find out. Henry hasn't got any money. Father wouldn't approve.\nBess: Well my duck, you need to hide your feelings better then! You're wearing your heart upon your sleeve; the whole world can see how you feel! Oh! Hello Mr Will…\nDaughter: Father!\nWill: Good afternoon Bess; Daughter… and what are you two gossiping about? Who's wearing their heart upon their sleeve?\nBess: We were …err… discussing that evil Iago, in your play Othello. He wears his heart upon his sleeve, doesn't he Mr Will?\nWill: Ah, yes, Othello, my tragedy. A very good topic for discussion. Iago says: I will wear my heart upon my sleeve…\nRobert Harley as Iago: I will wear my heart upon my sleeve: For daws to peck at. I am not what I am.\nWill: But, even though Iago talks about wearing his heart on his sleeve he doesn't actually intend to do it. Iago never reveals his true feelings, except perhaps to the audience, and even they cannot fully trust him!\nBess: Well, showing your true feelings certainly can lead to trouble.\nDaughter: What feelings does Iago hide, father? Is he in love?\nWill: No: quite the opposite. Iago pretends to be loyal to Othello so that he can destroy him! That's why he says: I am not what I am.\nNarrator: We'll leave them there for now. Many of Shakespeare's characters conceal their true feelings. Some hide their love, while Iago, Shakespeare's most hateful villain, hides his plans to destroy everyone around him. Nowadays, the phrase to wear your heart upon - or on - your sleeve still means: to make your feelings and emotions obvious, even if it makes you vulnerable. In a 2015 interview, US actress Kristen Stewart, star of the Twilight movies, said:\nClip 1: I wear my heart on my sleeve. If I'm in a mood, my mood shows.\nNarrator: It's often used to talk about love and romance.\nClip 2: When I told him I loved him, he broke up with me. I'll never wear my heart on my sleeve again.\nWill: Now, dear daughter, who is this young man who's made you so cheerful?\nDaughter: Oh… errr… nobody…\nWill: Nobody…?\nBess: Didn't I tell you not to wear your heart on your sleeve?!\nDaughter: Oh dear. To wear, or not to wear: that is the question…",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03vmqnn.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_wear_my_heart_upon_my_sleeve_download.mp3"
	},
	{
		"title"		: "Greek to me",
		"text"		: "Narrator: It’s October 1599. Shakespeare has finished writing his history play Julius Caesar and is visiting a fair in his home town of Stratford, with his daughter. She has just had her fortune told…\nWill: Now, dear daughter, what did Old Mother Howard say? What does the future hold for us, I wonder?\nDaughter: Oh father, Mother Howard talked a lot, but she had such a strange accent – I couldn't understand a word she said!\nWill: You're just like Casca in my play Julius Caesar.\nDaughter: Casca? He's one of the men that kills Caesar, the Roman general! How can you say that, father – I'm not a murderer!!!\nWill: Dear daughter, Casca was in a group of people who were listening to the great Roman speaker Cicero. But Cicero was speaking Greek, so Casca couldn't understand him.\nDaughter: Oh… why was Cicero speaking Greek?\nWill: That's what educated people spoke in Roman times. Casca says that some of the people listening to Cicero could actually understand him. Here are the lines: …those that understood him smiled at one another…\nThomas Swann as Casca: … those that understood him smiled at: one another and shook their heads; but, for mine own: part, it was Greek to me.\nDaughter: So Casca had no idea what Cicero was talking about. Just like me and Mother Howard!\nNarrator: We'll leave them there for now. Fortune tellers were common in Shakespeare's day, and they appear in many of his plays including Macbeth, the Comedy of Errors and Julius Caesar, in which the fortune teller warns Caesar to \"beware the Ides of March\" – the day on which Caesar was eventually assassinated by his closest friends. The phrase It was Greek to me has become It's all Greek to me in modern English, and it's used when something – not just a foreign language – is difficult to understand. For example, in a report about the 2015 Greek debt crisis, UK newspaper The Daily Telegraph carried the headline:\nClip 1: It's all Greek to me: a glossary of Eurozone crisis jargon\nClip 2: I'll never understand the rules of cricket: out for a duck, silly mid-off, googlies… It's all Greek to me!\nWill: Now tell me, daughter, did you understand anything Old Mother Howard said?\nDaughter: Yes! She talked about you, father. She said that you're going to be the most famous Englishman of all time! …but I think she was making it up.\nWill: Oh no, no, no… I'm sure she's absolutely right about that … She's obviously a very gifted woman. What shall we look at now, daughter?\nDaughter: Can we go to the gold stall father? Pleeeeeease???\nWill: I didn't need a fortune teller to predict that! To gold, or not to gold: that is the question.",
		"avatarURL"	: "https://ichef.bbci.co.uk/images/ic/320x180/p03w1lj5.jpg",
		"mediaURL"	: "https://downloads.bbc.co.uk/learningenglish/shakespeare/bbc_shakespeare_greek_to_me_download.mp3"
	}
]
