import * as g                           from '../../types/genetics'

export const ABC: g.snapMargin = [] as any;
export const MDL: g.OrganelleType[] = [ "dAudio", "rawText" ];
export const DNA: g.gene[] = [
	{
		title		: "Etwas durch die Blume sagen",
		text		: "Eine schreckliche Situation: Jemand, den man gerne mag, möchte eine ehrliche Meinung zu etwas. Aber die Wahrheit ist so unangenehm, dass man am liebsten weglaufen möchte. Für solche Situationen gibt es einen tollen Tipp!\n\n„Dieser schreckliche Hut! Wo hat sie ihn her? Und wie sage ich ihr, dass er einfach grauenhaft ist?“, denkt Marc. Währenddessen steht seine Freundin Hanna vor ihm und präsentiert stolz ihren neuen Hut. „Schau mal, Marc, das war ein richtiges Schnäppchen. Nur 120 Euro im Sonderangebot, das letzte Exemplar. In Paris tragen sie ihn alle!“ Marc weiß, dass er jetzt eine Antwort geben muss. Aber er kann ihr unmöglich sagen, dass sie aussieht wie eine verrückte Märchenfigur. Er möchte nicht, dass sie enttäuscht ist. Sie freut sich doch so sehr … Aber er möchte sie auch nicht anlügen. Also greift er zu einer besonderen Methode. Er sagt es ihr durch die Blume, also so, dass es nicht beleidigend ist: „Hanna, dieser Hut ist wirklich außergewöhnlich! Ich glaube, ich habe auch schon ein Foto davon gesehen. Wie heißt noch mal diese verrückte Modedesignerin aus Paris? Ja, ich glaube, sie trägt ihn auch ganz gerne. Ganz toll! Es ist nur ein bisschen schade, dass die blaue Farbe nicht so ganz zu dem wunderschönen Blau deiner Augen passt. Aber wichtig ist nur, dass er dir gefällt.“ „Meinst du wirklich?“, sagt Hanna nachdenklich. Dann kramt sie noch mal in ihrer Handtasche nach der Quittung. Vielleicht kann sie den Hut zurückgeben? Auch wenn Marc ihn ganz gerne mag …",
		avatarURL	: "https://www.dw.com/image/18842667_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/5E2C843A_2.mp3"
	},
	{
		title		: "Einen Korb bekommen",
		text		: "Was ist an einem Korb so schlimm? Eigentlich gar nichts! Körbe sind schön und praktisch. Einen Korb voll mit Obst zu bekommen, ist zum Beispiel sehr schön. Aber manche Körbe bekommt niemand gerne.\n\nAnna geht ans Telefon: „Hallo Michael, schön von dir zu hören!“ Sie lässt das „schön“ bewusst ironisch klingen. Michael ist Annas bester Freund, aber er war in den letzten Wochen damit beschäftigt, einer schönen Blondine namens Katharina hinterherzulaufen. Anna und er haben schon lange nicht mehr miteinander telefoniert. Jetzt erzählt Michael, was er in den letzten Wochen alles erlebt hat: Er hat Katharina jeden Tag nach der Uni nach Hause begleitet. Er hat ihr Blumen geschenkt. Er hat sogar auf ihren Hund aufgepasst. Aber als er mit ihr ins Theater gehen wollte, hat sie Nein gesagt. „Stell dir vor“, sagt Michael zu Anna: „Ich habe die besten und teuersten Karten gekauft. Aber sie hat mir eiskalt einen Korb gegeben. Einfach so. Sie hat gesagt, dass ich nur ein guter Freund bin, mehr nicht.“ Anna ist nicht überrascht. „Kein Wunder, dass du einen Korb bekommen hast. Ich habe dir von Anfang an gesagt, dass sie nicht auf dich steht.“ „Du hattest ja recht“, antwortet Michael, „ich hätte auf dich hören müssen. Und es tut mir leid, dass ich mich nicht gemeldet habe. Vielleicht hast du ja Lust, mit mir ins Theater zu gehen?“ Anna denkt nach. „Ach, ich glaube, ich habe keine Lust drauf. Frag lieber jemand anderen.“ Dann legt Anna auf. Michael ist geschockt. Zwei Körbe an zwei Tagen, das hat er nun wirklich nicht verdient! Oder doch?",
		avatarURL	: "https://www.dw.com/image/18823092_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/4D63EFC6_2.mp3"
	},
	{
		title		: "Im Eimer sein",
		text		: "So richtig gemütlich ist es in einem Eimer nicht. Wenn man aber nicht aufpasst, kann man ganz schnell dort landen. Doch wie kann man es vermeiden, im Eimer zu enden?\n\nWas für eine Woche! Am Montag kam die neue Sommerkollektion. Bis Mitternacht hat Ellen Kartons ausgeräumt. Am Dienstag war ihr Laden proppenvoll, weil alle sich die neuen Kleidungsstücke angucken wollten. Am Mittwoch wollte ihr Auto nicht anspringen und Ellen hat ewig gebraucht, um zur Arbeit zu kommen. Donnerstags besucht sie einen Tangokurs – das ist ein Pflichttermin für sie. Am Freitag musste Ellen nach Ladenschluss noch die Hochzeitstorte ihrer Schwester abholen. Die Hochzeitsfeier am Samstag war dann wunderschön, aber irgendwie auch anstrengend! Und Ellen hatte versprochen, die Verwandten, die aus Norddeutschland extra für die Hochzeit angereist waren, am Sonntag zurück zum Bahnhof zu begleiten. Als am Sonntagabend ihre Mutter anruft, sagt Ellen: „Mutti, mein Auto ist im Eimer und ich bin es auch. Ich habe die ganze Woche nur Stress gehabt und bin jetzt total kaputt.“ Dabei liegt sie auf dem Sofa und kuschelt sich an ihr Kissen. Erholung ist das Einzige, was sie jetzt braucht. Dann kommt Ellen vielleicht aus dem „Eimer“ wieder raus. Denn am Montag geht der Alltagswahnsinn wieder los.",
		avatarURL	: "https://www.dw.com/image/18870608_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/8574E304_2.mp3"
	},
	{
		title		: "Jemanden auf die Palme bringen",
		text		: "Auf Bäumen sitzt man nicht besonders bequem. Manchmal gibt es aber Menschen, die so nervig sind, dass man am liebsten auf einen Baum klettern möchte. Dafür scheint ein bestimmter Baum besonders geeignet zu sein.\n\nPaul weiß immer alles besser: „Linda, nimm nicht so viel Kaffeepulver für die Kaffeemaschine, sonst schmeckt der Kaffee wieder bitter“, sagt er, „Italiener nehmen immer nur vier Löffel Kaffee pro Person, so kommt das Aroma besser zur Geltung.“ Linda ist gerade aufgestanden und hat keine Lust, sich einen Kaffee-Vortrag anzuhören. Sie ignoriert ihren Mitbewohner und bereitet weiter ihr Frühstück vor. „Du solltest das Brot in dünnere Scheiben schneiden, sonst bleibt es im Toaster stecken“, bemerkt Paul. Linda beißt die Zähne zusammen. „Weiß du, wie viel Zucker in dieser Marmelade steckt? Das ist ungesund!“, hört sie Paul sagen. Linda nimmt einen Extralöffel von der Marmelade. Paul wirft einen Blick auf Lindas Schuhe: „Hast du die Wettervorhersage für heute nicht gehört? Es soll regnen!“ „Ich habe aber gerne nasse Füße“, erwidert Linda nun offensichtlich genervt. „Was ist mit&nbsp;dir los, Linda, hast du schlecht geschlafen?“, fragt Paul. „Nein. Ich habe hervorragend geschlafen. Nur du bringst mich mit deiner Besserwisserei auf die Palme!“ Bevor Paul etwas sagen kann, hat Linda die Haustür mit einem großen Knall hinter sich zugeworfen.",
		avatarURL	: "https://www.dw.com/image/18825419_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/1F6CAA0B_2.mp3"
	},
	{
		title		: "Auf Wolke sieben schweben",
		text		: "Manchmal fühlt sich das Leben einfach schön an. Die Sonne scheint, die Vögel singen, der Himmel ist blau, alles ist perfekt. Der Grund dafür ist meistens einfach: Man ist verliebt.\n\nManchmal ist das Leben einfach perfekt. Neulich war Diana im Supermarkt. Ein Mann kam auf sie zu und fragte: „Kannst du mir helfen? Was bedeutet ‚Sahne‘?“ Während Diana erklärt, was „Sahne“ ist, bemerkt sie, dass der Mann wunderschöne Augen hat. „Ich bin aus Kanada“, sagt er. „Kanada, mein Lieblingsland!“, denkt Diana und stellt aber sofort etwas enttäuscht fest: „Wenn er aus Kanada ist, bleibt er bestimmt nicht lange in Deutschland … Schade!“ Der schöne Mann bedankt sich für die Hilfe. „Ich lerne gerade Deutsch, weil ich hier leben möchte“, erklärt er. Dann schaut er auf die Uhr: „Ich muss gehen.“ „Ach, wenn er gehen MUSS, hat er bestimmt eine Freundin …“, spekuliert Diana. „Mein Hund wartet auf mich, ich muss mit ihm spazieren gehen!“, fügt der Mann hinzu. „Ein Tierliebhaber!“ schwärmt Diana. Der schöne Mann möchte gerade los, aber er dreht sich noch ein letztes Mal um: „Vielleicht sehen wir uns wieder?“ „Gerne“, sagt Diana und schreibt ihm ihre Telefonnummer auf. Heute hat er angerufen. Seitdem schwebt Diana auf Wolke sieben. Das Leben ist halt manchmal einfach perfekt.",
		avatarURL	: "https://www.dw.com/image/18825417_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/26728D94_2.mp3"
	},
	{
		title		: "Leben wie Gott in Frankreich",
		text		: "Es gibt ein Land, das so schön ist, dass selbst Gott dort leben möchte. Die Menschen in diesem Land genießen den Tag, haben ganz viel Geld und keine Sorgen. Zumindest behauptet das eine Redewendung.\n\nSabrina ist genervt und ein wenig neidisch: Ihre Freundin Tina fährt mindestens dreimal im Jahr in Urlaub, geht jedes Wochenende shoppen und auch sonst ist ihr Leben wie aus einem Märchenbuch. Klar, Tina verdient ja auch viel Geld als Managerin. Sabrina findet: Tina lebt wie Gott in Frankreich! Das bedeutet natürlich nicht, dass sie eine Göttin ist oder dass sie in Frankreich lebt. Tina ist eine ganz normale Frau. Sie lebt in Köln und fliegt am liebsten nach Australien. Sie kann sich einfach alles leisten und genießt das Leben. So stellen sich manche Leute das Leben in Frankreich vor. Sonne, Liebe in der Luft, Rotwein, guter Käse und schöne Landschaften, den ganzen Tag „oh, là là“ rufen und es sich gutgehen lassen. Ob das realistisch ist? Fragt doch mal einen Franzosen …",
		avatarURL	: "https://www.dw.com/image/18825422_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/4F67B502_2.mp3"
	},
	{
		title		: "Den Nagel auf den Kopf treffen",
		text		: "Einen Nagel gerade in die Wand schlagen: Das geht mit der richtigen Technik und einem guten Hammer. Man kann aber auch mit Worten den Nagel auf den Kopf treffen. Und auch dazu braucht man die richtigen Werkzeuge.\n\nKatja ist Journalistin. Sie schreibt für eine regionale Zeitung in ihrer Heimatstadt Bonn. Ihre Artikel werden online veröffentlicht und auch auf Facebook gepostet. Katja liest gerne die Kommentare im Netz, denn die Meinung der Leser interessiert sie. Seit gestern ist Katja aber ein kleiner Star. Sie hat einen Artikel über den Zustand der Bonner Schulen geschrieben. Sie kritisiert darin die Stadtverwaltung, weil sie nicht genug Geld in die Sanierung der Schulgebäude stecke. Damit hat sie ein Thema angesprochen, das viele bewegt: Ihr Artikel wurde über 20.000 Mal geteilt und tausendfach kommentiert. Die meisten User geben ihr recht. Die junge Mutter Marina Koch schreibt zum Beispiel: „Liebe Katja, Sie treffen mit Ihrem Artikel wirklich den Nagel auf den Kopf. Ich kann Ihnen nur zustimmen: Die Stadt sollte viel mehr für unsere Kinder tun. Danke!“ Katja freut sich. Die Kommentare zeigen ihr, dass sie die richtigen Worte gefunden hat. Jetzt stellt sich nur noch die Frage: Wird die Stadt etwas an ihrer Politik ändern?",
		avatarURL	: "https://www.dw.com/image/19035597_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/C68CC1D7_2.mp3"
	},
	{
		title		: "Geld zum Fenster hinauswerfen",
		text		: "Mit Geld kann nicht jeder umgehen. Der eine spart jeden Cent, während der andere schon am Monatsanfang wieder pleite ist und gar nicht weiß, wofür er das Geld eigentlich ausgegeben hat.\n\nAnnika und Jens sind schon lange ein Paar. Beide studieren und haben eine gemeinsame Haushaltskasse. Aber so langsam reicht es Annika, denn Mitte des Monats ist kaum mehr Geld für Lebensmittel in der Kasse. Dafür präsentiert Jens ihr stolz Haushaltsgeräte, die kein Mensch braucht. Einen Flaschenöffner in Fußballform zum Beispiel oder einen Apfelschäler. Und letzten Monat gab es eine teure Maschine, mit der man Rührei machen kann. All die schönen Geräte stehen in der Küche herum und sind bisher kaum benutzt worden. Annika hat das Gefühl, dass Jens ihr Geld einfach zum Fenster hinauswirft. Aber Jens ist ganz sicher: Diese Geräte steigern die Lebensqualität und machen den Alltag leichter. Annika hat momentan einen Wunsch: einen Roboter kaufen, der Jens ersetzt. Das wäre gut angelegtes Geld, und der Roboter würde ihr viel Arbeit abnehmen, zum Beispiel endlich die Fenster putzen.",
		avatarURL	: "https://www.dw.com/image/18845463_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/7D5E7D56_2.mp3"
	},
	{
		title		: "Jemandem Honig um den Bart schmieren",
		text		: "Manche Leute lassen sich nicht so einfach überzeugen. Sie brauchen immer ein wenig Überzeugungsarbeit. Und bei manchen können ein paar nette Worte nicht schaden, denn wer bekommt nicht gerne ein Kompliment?\n\nHerr Knaus, Bettinas Chef, ist eigentlich ein netter Mensch, aber er kann es nicht so gut zeigen. Manchmal sagt er ganz ohne Grund Nein zu Dingen, die ganz sinnvoll wären. Bettina braucht zum Beispiel ein bisschen mehr Budget für ihr neues Projekt. Herr Knaus ist aber gar nicht begeistert. Wo soll er das Geld herholen? Und wer garantiert ihm, dass Bettina nicht wiederkommt und noch ein höheres Budget braucht? Also greift Bettina zu einem kleinen Trick: Sie schmiert ihm Honig um den Bart. Natürlich greift sie nicht zu echtem Honig, sondern zu netten Worten und Komplimenten. Kurz: Sie schmeichelt ihm. Herr Knaus kenne das Geschäft ja besser als sie, ein Mann mit seiner Erfahrung wisse ja, wie das ist. Mit ein bisschen mehr Geld könne man neue Software kaufen und sich einen besseren Programmierer leisten. Am Ende sei das ja nur ein Gewinn für die Firma. Und wenn dieses Projekt gelänge, könne Herr Knaus auch endlich die Anerkennung bekommen, die er verdiene. Die Firma würde sich vor neuen Aufträgen nicht retten können. „Stopp“, ruft Herr Knaus: „Sie bekommen ja Ihr Budget. Und jetzt hören Sie auf, mir Honig um den Bart zu schmieren. Natürlich sehe ich die Vorteile selbst. Ich arbeite ja schon lange in dieser Branche.“ Bettina bedankt sich und verlässt zufrieden das Büro ihres Chefs. Herr Knaus lächelt. Er hat wieder eine gute Entscheidung getroffen.",
		avatarURL	: "https://www.dw.com/image/18823093_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/5B514CDB_2.mp3"
	},
	{
		title		: "Eigenlob stinkt",
		text		: "Selbstbewusste Menschen haben es leichter im Leben. Sie beeindrucken andere durch ihre Fähigkeiten und Talente. Aber wenn sie nur von sich reden und mit ihrem Können angeben, kann das die Umwelt auch ganz schön nerven.\n\n„Ich bin der beste Radfahrer dieser Stadt“, behauptet Peter. Lisa verdreht die Augen. Die Geschichten über Peters Radfahrkünste hat sie sich schon tausendmal anhören müssen. Wenn Peter am Wochenende mit dem Rad unterwegs gewesen ist, hat er am Montagmorgen in der Bahn ein einziges Thema: „Ich bin blitzschnell“, „Ich habe den schärfsten Gehörsinn der Welt“, „Keiner hat solche Reflexe wie ich“, „Ich bin der König der Straße“, „Ich habe das und jenes geschafft“, „100 Kilometer an einem Tag? Ja, das ist doch ganz leicht!“... Normalerweise tut Lisa so, als würde sie sich für Peters Erzählungen interessieren, und versucht, an was anderes zu denken. Aber heute verliert sie die Nerven. „Weißt du was, Peter? Eigenlob stinkt!“, sagt sie. Peter verstummt nachdenklich. Dann schnüffelt er an seinen Achseln. „Du, das muss mein neues Deodorant sein. Ich kaufe morgen direkt ein besseres!“ Lisa gibt auf. Manche Menschen sind einfach unverbesserlich.",
		avatarURL	: "https://www.dw.com/image/18823096_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/043B29A8_2.mp3"
	},
	{
		title		: "Ein Auge zudrücken",
		text		: "Wenn man seine Ruhe haben will, hilft es manchmal, die Augen zu schließen und an etwas Schönes zu denken. Aber was bedeutet es, wenn man nur ein Auge schließt beziehungsweise zudrückt?\n\nEs gibt Situationen, da möchte man lieber wegschauen oder so tun, als hätte man nichts gesehen. Aber manchmal geht es nicht anders. Wie im Fall von Irene, die als Managerin in einem noblen Restaurant arbeitet. Der neue Kellner Roman ist ziemlich tollpatschig. Immer wieder fällt ihm etwas aus der Hand oder er gießt den Wein daneben. Das nervt ein bisschen. Aber Irene – und die Gäste übrigens auch – können Roman nicht so richtig böse sein und drücken immer wieder ein Auge zu. Denn Roman ist der charmanteste Mensch der Welt. Hat er mal wieder den Wein danebengegossen, entschuldigt er sich so nett beim Gast, dass dieser ihm sofort verzeiht. Und fällt ihm in der Küche ein Teller aus der Hand, so fegt er sofort die Scherben auf und macht alles wieder sauber. Selbst der Chefkoch konnte sich vor ein paar Tagen nicht so richtig aufregen, obwohl Roman versehentlich Zucker in die Suppe getan hatte. „Wollen wir mal nicht so sein!“, sagte er zu Roman, der sich reumütig entschuldigte. „Ich will mal ein Auge zudrücken!“",
		avatarURL	: "https://www.dw.com/image/19054082_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/E37ABE47_2.mp3"
	},
	{
		title		: "Einen Kater haben",
		text		: "Es fängt meistens so an: Die Party ist gut, alle Freunde sind da, der Alkohol fließt, die Stimmung steigt. Es ist seit langer Zeit die beste Party! Aber irgendwann wacht man auf, und er ist da! Wer hat ihn bloß gerufen?\n\nMarie war gestern mit ihren Freunden aus. Eigentlich wollten sie irgendwo gemütlich sitzen und ein Bier trinken. Doch dann kamen immer mehr Freunde dazu, und am Ende landeten alle auf einer coolen Party. Der DJ legte genau die richtige Musik auf, die Stimmung war fantastisch, und irgendwie hatte Marie andauernd einen neuen Drink in der Hand. Wann sie genau nach Hause kam, weiß sie heute Morgen nicht mehr, aber … aua … diese Kopfschmerzen! Die müssen doch wirklich nicht sein! Und … aua … jetzt klingelt auch noch das Telefon. „Hallo, Marie?“ Es ist Bettina, Maries Freundin. „Ich wollte nur wissen, ob es dir gut geht und du gestern gut nach Hause gekommen bist.“ „Ach ja ...“, seufzt Marie: „… alles gut. Wenn nur diese Kopfschmerzen nicht wären. Und mein Magen erst … Ich glaube, das letzte Bier war schlecht.“ Bettina lacht: „Tja, da hast du wohl einen richtigen Kater! Trink viel Wasser und iss was Salziges. Gute Besserung!“ Marie legt auf. Auf diesen Kater könnte sie gut verzichten. In Maries Fall ist das nämlich kein süßes Haustier, sondern die Bezeichnung für die schmerzhaften Folgen von zu viel Alkohol. „Aua! Ich werde nie wieder trinken!“, sagt Marie. „Das werden wir sehen …“, sagt der Kater.",
		avatarURL	: "https://www.dw.com/image/18821568_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/F6252F10_2.mp3"
	},
	{
		title		: "Das Haar in der Suppe suchen",
		text		: "Ein Haar in der Suppe? Das möchte doch niemand haben. Aber es gibt tatsächlich Menschen, die extra danach suchen. Und sie freuen sich, wenn sie ein Haar in der Suppe gefunden haben. Aber warum ist das so?\n\nAnton ist sauer. Sechs Monate lang hat er an einem wichtigen Projekt gearbeitet. Sein Abschlussbericht war perfekt. Ausführlich, detailliert, sachlich. „Ich habe alles reingeschrieben, was er wissen soll!“, sagt Anton beleidigt. Mit „er“ ist sein Chef gemeint, der schwer zufriedenzustellen ist. Oder wie es Anton ausdrücken würde: „Man kann es ihm nie Recht machen!“ Antons Chef sucht gerne das Haar in der Suppe. Das heißt natürlich nicht, dass er jeden Suppenteller nach Haaren durchsucht, sondern dass er oft das Schlechte hervorhebt und dabei viel Gutes übersieht. Diesmal gefiel ihm die Nummerierung der Seiten an Antons Bericht nicht. „Unten rechts, Anton, die Seitennummern immer unten rechts! Darauf sollten Sie beim nächsten Mal achten!“, war sein einziger Kommentar zu Antons Bericht. Antons Freund Luigi versucht, ihn zu trösten: „Ärgere dich nicht! Ich glaube, dein Chef ist mit seinem eigenen Leben so unglücklich, dass er unbedingt auch andere unglücklich machen muss. Deswegen sucht er immer ein Haar in jeder Suppe.“",
		avatarURL	: "https://www.dw.com/image/18821570_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/0A306620_2.mp3"
	},
	{
		title		: "Jemandem die Daumen drücken",
		text		: "Es gibt viele Arten, einander Glück zu wünschen. Man kann „viel Erfolg!“ sagen oder jemandem die Daumen drücken. Ob es hilft? Immerhin: Wer freut sich nicht darüber, dass an ihn gedacht wird?\n\nGloria hat morgen Führerscheinprüfung. Sie ist gut vorbereitet, hat aber dennoch Angst. Was ist, wenn der Prüfer einen schlechten Tag hat und sie mit schwierigen Aufgaben quält? Was ist, wenn es die ganze Zeit regnet und sie nichts sehen kann? Und was ist, wenn sie zu nervös ist, um richtig einzuparken? Zu ihrer Schwester Greta sagt sie: „Drück mir bitte die Daumen, dass alles gut geht!“ Greta versteht die Ängste ihrer Schwester gut. „Es bringt überhaupt nichts, nervös zu sein“, sagt sie. „Ich drücke dir die Daumen. Du schaffst das alles.“ Natürlich besteht Gloria die Führerscheinprüfung. Zu ihrer Schwester sagt sie: „Danke, dass du mir die Daumen gedrückt hast. Das hat mir wirklich geholfen!“ „Quatsch!“, sagt Greta, „Ich hab zwar fest an dich geglaubt, aber das hast du ganz allein geschafft!“",
		avatarURL	: "https://www.dw.com/image/19035582_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/F677E998_2.mp3"
	},
	{
		title		: "Liebe geht durch den Magen",
		text		: "Woher kommt die Liebe, wohin geht die Liebe? Das ist ein großes Geheimnis. Wenn man aber einem Sprichwort glaubt, dann hat die Liebe ganz viel mit einem Organ zu tun, das wir normalerweise nicht romantisch finden.\n\nEmilie und Adrian kennen sich nicht so lange, aber es ist ganz klar: Sie finden einander interessant. Emilie ist sich nicht ganz sicher, wie Adrians Gefühle für sie sind. Mag er sie oder hat er stärkere Gefühle für sie? Zeit für einen kleinen Trick. Denn Emilies Großmutter hat immer gesagt: „Mein Kind, Liebe geht durch den Magen! Dein Großvater hat meinen Gulasch so gerne gegessen, dass er bis heute bei mir geblieben ist!“ Also lädt Emilie Adrian zum Essen ein. Es gibt Spaghetti mit leckerer Soße und selbst gemachtes Eis. Und es funktioniert: Während die beiden am Tisch sitzen und das Eis löffeln, schaut Adrian Emilie tief in die Augen und stellt fest: Ich hab diese Frau zum Fressen gern. Ob es am Essen liegt oder an Emilies schönen Augen? Die Großmutter würde sagen: Am Essen natürlich, denn Liebe geht durch den Magen. Emilie und Adrian heiraten übrigens nächstes Wochenende. Ihr seid herzlich eingeladen.",
		avatarURL	: "https://www.dw.com/image/18821567_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/AE36FC74_2.mp3"
	},
	{
		title		: "Da ist der Wurm drin",
		text		: "Das hat wahrscheinlich jeder schon mal erlebt: Man probiert etwas aus und es funktioniert nicht. Und dann noch mal. Und noch mal. Egal, wie man sich anstellt, es klappt nicht! Da muss der Wurm drin sein …\n\nUli hat ein Problem: Er hat sich vor drei Wochen einen neuen Rechner gekauft, das neueste und teuerste Modell. Aber irgendwie macht der Rechner nicht das, was er tun soll. Schon das Hochfahren klappt nicht immer, ein neuer Browser lässt sich nicht installieren, und dann ist da immer wieder diese seltsame Fehlermeldung. Eigentlich versteht Uli viel von Computern, aber hier ist er wirklich ratlos. Also bringt er den Rechner zurück in den Laden. Der Fachverkäufer im Computerladen ist zunächst nicht besonders freundlich. „Sind Sie ganz sicher, dass Sie alles richtig installiert haben?“, fragt er Uli, „unsere Kunden waren bisher immer zufrieden. Es hat sich niemand über dieses Modell beschwert.“ „Das kann ja sein“, sagt Uli, „aber bei mir scheint einfach der Wurm drin zu sein. Irgendwas ist hier fehlerhaft.“ Der Fachverkäufer erklärt sich schließlich bereit, den Rechner umzutauschen. Der neue Computer läuft problemlos. Kein Wurm weit und breit. Uli ist erleichtert.",
		avatarURL	: "https://www.dw.com/image/19084971_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/D793A41C_2.mp3"
	},
	{
		title		: "Jemanden um den Finger wickeln",
		text		: "Es gibt Menschen, die immer bekommen, was sie wollen, ganz ohne Druck oder Gewalt. Sie haben ein ganz besonderes Talent, andere zu manipulieren, ohne dass diese es wirklich merken. Aber wie machen sie das?\n\n„Sie wickelt dich immer um den Finger“, sagt Peter. Sein bester Freund Leo sitzt ihm gegenüber und fragt erstaunt: „Wie meinst du das?“ Peter erinnert ihn an das Fußballturnier letzten Sommer. Leo hat nicht mitspielen können, weil seine Freundin unbedingt dieses Wochenende am Strand verbringen wollte. „Sie war von der Arbeit so gestresst …“, versucht Leo zu erklären. „Und was ist mit Jörgs Geburtstag? Da warst du auch nicht dabei“, kontert Peter. „Ja, da hatte gerade das neue Restaurant aufgemacht, und sie wollte es unbedingt ausprobieren“, redet sich Leo wieder raus. „Früher haben wir uns jeden Donnerstag zu einem Feierabendbier getroffen …“, bemerkt Peter. „Aber Donnerstag ist unser Kinoabend …“, erwidert Leo. „Und die Weihnachtsfeier?“, möchte Peter wissen. „Wir gehen zu einem Konzert. Sie hat Karten organisiert, und das war ganz schön schwer. Und sie freut sich so sehr darauf!“, erzählt Leo. „Sag ich doch“, sagt Peter. „Sie wickelt dich immer um den Finger, und du merkst es einfach nicht.“ Leo zuckt mit den Schultern. Er denkt an das zufriedene Lächeln seiner Freundin und den Glanz in ihren schönen Augen, als er ihr versprochen hat, mit ihr zu dem Konzert zu gehen. „Du bist der Beste!“, hatte sie gesagt. Dieser Satz ist für ihn schöner als jede Weihnachtsfeier.",
		avatarURL	: "https://www.dw.com/image/18842671_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/D933A32F_2.mp3"
	},
	{
		title		: "Die halbe Miete sein",
		text		: "Kein Vermieter der Welt würde sich einfach so mit der halben Miete zufriedengeben. Aber es gibt Situationen im Leben, da sollte man sich freuen, dass man immerhin die halbe Miete zusammenbekommen hat.\n\nAnja und Fatima arbeiten schon lange zusammen. Mittlerweile sind sie sogar Freundinnen und erzählen sich alles. Seit einiger Zeit ist Anja ein wenig nachdenklich. Daher spricht Fatima ihre Freundin in der Mittagspause darauf an. „Du, ich hab das Gefühl, dass dich etwas bedrückt. Magst du mir von deinen Sorgen erzählen?“ „Ja, du hast recht“, sagt Anja, „es gibt momentan so viele Dinge, die ich erledigen muss. Mein größtes Problem ist, dass ich für meine kleine Tochter einen Platz in einer Kindertagesstätte suche. Aber die Suche ist wirklich schwierig. Es gibt einfach keine freien Plätze in den Kitas in unserer Nähe …“ Fatima nickt mitfühlend. „Ich kenne das Problem“, sagt sie zu Anja. „Du weißt ja, dass ich auch lange einen Kitaplatz für meinen Sohn gesucht habe. Aber vielleicht könnte ich dir helfen. Ich kenne nämlich die Leiterin einer Kindertagesstätte ganz in deiner Nähe.“ „Und du meinst, du könntest mit der Leiterin reden?“ „Na klar“, sagt Fatima, „ich kenne sie wirklich ganz gut.“ „Das ist ja schon mal die halbe Miete“, sagt Anja hoffnungsvoll, „wenn du mir da helfen könntest, wäre ich dir sehr dankbar.“",
		avatarURL	: "https://www.dw.com/image/19084999_302.png",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/1F69791B_2.mp3"
	},
	{
		title		: "Tomaten auf den Augen haben",
		text		: "Viele Menschen legen sich manchmal Gurken auf die Augen, um sie zu pflegen. Tomaten benutzt man dafür nicht. Trotzdem haben manche Leute oft Tomaten auf den Augen. Dabei kann das sogar gefährlich werden.\n\nSandra kommt gerade von einem Bewerbungsgespräch. Sie kann nicht aufhören, daran zu denken. Hat sie einen guten Eindruck gemacht? Oder hat sie sich schlecht benommen? Sandra ist in Gedanken noch ganz bei dem Gespräch und läuft so durch die Straßen der Stadt. Natürlich bemerkt sie deshalb das heranfahrende Auto nicht. Sie läuft einfach auf die Straße, ohne zu gucken. Quietschend und qualmend macht das Auto eine Vollbremsung. Sandra erschrickt. Nur wenige Meter vor ihr bleibt das Auto stehen. Der Fahrer schreit wütend aus dem Fenster: „Sag mal, hast du Tomaten auf den Augen?“ Dann rast er davon. Sandra schüttelt den Kopf. „Frechheit!“, denkt sie. Sie war nur nicht sehr aufmerksam. Moment mal, war sie im Bewerbungsgespräch etwa auch nicht aufmerksam genug? Und KNALL! Sandra ist gegen eine Laterne gelaufen. Sie sollte wirklich erst nach Hause gehen und sich dort in Ruhe ihre Gedanken machen.",
		avatarURL	: "https://www.dw.com/image/19185261_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/01A6D1F5_2.mp3"
	},
	{
		title		: "Jemandem rutscht das Herz in die Hose",
		text		: "Normalerweise verbindet man das Herz mit Liebe und Romantik. Man kann zum Beispiel sein Herz an jemanden verlieren oder jemandem das Herz brechen. Aber was bedeutet es, wenn einem das Herz in die Hose rutscht?\n\nFred ist ein Abenteurer. Er geht gerne in fremden Ländern auf Reisen und er liebt Ziele fernab der großen Touristenmagnete. Er ist mutig und hat weder Angst vor giftigen Spinnen noch steilen Abhängen. Dieses Jahr flog Fred nach Namibia, um sich endlich einen großen Wunsch zu erfüllen: exotische Tiere in freier Wildbahn beobachten. Und tatsächlich wurden seine Erwartungen erfüllt. In den weiten Landschaften Namibias konnte Fred Zebras, Giraffen und Elefanten aus nächster Nähe bewundern. Mit seiner Kamera machte Fred Fotos für seine Freunde zu Hause. Aber dann passierte etwas, womit er nicht gerechnet hatte: Fred war gerade damit beschäftigt, eine Gruppe Giraffen zu fotografieren, als er hinter sich ein Geräusch hörte. Er drehte sich langsam um und stand einem riesigen Löwen gegenüber! „Zum ersten Mal in meinem Leben“, erzählte er später seinen Freunden zu Hause, „dachte ich, dass ich nicht lebend nach Hause komme. Mir ist das Herz in die Hose gerutscht.“ Zum Glück behielt Fred in dieser Situation doch noch einen kühlen Kopf. Er blieb ruhig stehen und tat einfach nichts. Der Löwe schaute ihn eine Zeit lang an und machte sich dann auf den Weg zu den Giraffen. Glück gehabt! Nächstes Jahr möchte Fred unbedingt nach London. Den Buckingham Palace wollte er schon immer sehen …",
		avatarURL	: "https://www.dw.com/image/19084990_302.png",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/94AFCDFB_2.mp3"
	},
	{
		title		: "Unter den Fingernägeln brennen",
		text		: "Wenn etwas brennt, kann man die Feuerwehr rufen oder einen Eimer Wasser holen. Gegen das Feuer unter den Fingernägeln hilft das aber nicht. Dann sollte man besser sagen, was man schon lange loswerden wollte.\n\nJenny ist Journalistin und schreibt gerne über Prominente und bekannte Personen. Heute war sie besonders aufgeregt, denn sie hatte einen Interviewtermin mit einem bekannten Schauspieler. Leider hatte sie nur 20 Minuten Zeit für das Interview. Nach 15 Minuten redete der Schauspieler immer noch ohne Punkt und Komma über seinen neuen Film, ohne dass Jenny überhaupt eine Frage stellen konnte. Der Manager des Schauspielers kam herein, um Bescheid zu sagen, dass Jenny nur noch fünf Minuten Zeit hatte. „Falls Ihnen noch eine Frage unter den Nägeln brennt, sollten Sie diese jetzt stellen …“, riet er ihr. „Mir brennt tatsächlich etwas sehr unter den Nägeln“, sagte Jenny, „könnte es sein, dass Ihre drei Ehen daran zerbrochen sind, dass sie zu viel geredet haben?“ Eine Antwort auf diese Frage bekam Jenny leider nicht. Dabei hätte sie diese wirklich sehr interessiert.",
		avatarURL	: "https://www.dw.com/image/19084989_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/A6AA3D64_2.mp3"
	},
	{
		title		: "Etwas an den Nagel hängen",
		text		: "Manche Leute wissen ganz genau, wann der richtige Zeitpunkt da ist, um etwas zu beenden. Dann hängen sie etwas an den Nagel, und damit ist nicht die Jacke oder die alte Strickmütze gemeint …\n\nFrau Becker arbeitete 20 Jahre lang als Abteilungsleiterin in ihrer Firma. Sie ging immer gerne zur Arbeit und war bei ihren Kollegen beliebt. In den letzten zwei Jahren hatte Frau Becker aber langsam das Gefühl, dass die Arbeit sie nicht mehr ausfüllte. Wenn sie morgens ins Büro kam, wollte sie am liebsten wieder weg. Sie wollte viel lieber ein Kinderbuch schreiben, Reiseleiterin werden oder eine Ausbildung zur Yogalehrerin machen. Und dann tat sie es einfach: Sie hängte ihren Job an den Nagel und fuhr nach Australien. Ihrer besten Freundin schickte Frau Becker vor kurzem eine Postkarte, auf der stand: „Meine Karriere an den Nagel zu hängen, war die beste Entscheidung meines Lebens. Ich habe hier ein ganz neues Leben angefangen und bin der glücklichste Mensch der Welt.“ Ja, manche Leute wissen ganz genau, wann es Zeit ist, mit etwas aufzuhören.",
		avatarURL	: "https://www.dw.com/image/19084997_302.png",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/28B69E42_2.mp3"
	},
	{
		title		: "Die Kuh vom Eis holen",
		text		: "Probleme gibt es im Leben genug. Ständig bekommt man neue Aufgaben, die man erfolgreich lösen muss. Doch es gibt manche Herausforderungen, die so groß sind, dass man daraus ein Sprichwort machen muss.\n\nDie Lehrerin Frau Schulte trifft sich mit Martins Eltern zu einem Gespräch. „Es gibt ein Problem mit Martin“, sagt Frau Schulte, „er ist seit dem ersten Schultag mit einem Mitschüler verfeindet. Fast jeden Morgen beschimpfen und prügeln sie sich. Und ansonsten reden sie überhaupt nicht miteinander. Das stört die Atmosphäre in unserer Klasse!“ Martins Eltern sind entsetzt. „Das kann ich gar nicht glauben, Martin ist doch so ein lieber Junge“, ruft der Vater. Frau Schulte sagt: „So kann es auf jeden Fall nicht weitergehen. Auch die Mitschüler leiden unter den ständigen Aggressionen. Also, wie holen wir die Kuh vom Eis?“ Der Vater weiß keine Lösung für das Problem. Martins Mutter schlägt vor: „Wir reden mit den Eltern des anderen Schülers. Vielleicht können wir ja zusammen mit den Kindern ein Eis essen gehen, und die beiden Jungen vertragen sich.“ Die Lehrerin nickt. „Eine gute Idee. Aber das wird nicht einfach und könnte für alle schnell peinlich werden.“ Doch Martins Mutter ist sich sicher, dass sie das schafft.",
		avatarURL	: "https://www.dw.com/image/19185255_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/FCBF2566_2.mp3"
	},
	{
		title		: "Hinter dem Mond leben",
		text		: "Nur wenige Menschen waren bisher auf dem Mond und noch weniger dahinter. Dennoch gibt es Leute, die wirken, als würden sie nicht auf der Erde, sondern viel weiter weg wohnen …\n\nMelanie ist eine sehr nette Frau. Ihre Freunde mögen sie gerne, nur manchmal wundern sie sich über gewisse Dinge, die Melanie sagt oder fragt. Letzte Woche hat sich Melanie Daniels Musiksammlung angeguckt und wollte wissen, ob Michael Jackson nicht was Neues rausgebracht hätte. „Meinst du DEN Michael Jackson, der 2009 gestorben ist?“, fragte Daniel erstaunt. Vor Kurzem dachte Melanie, eine super Idee zu haben: „Man könnte eine Internetseite aufbauen, um mit Freunden und Bekannten aus der ganzen Welt im Kontakt zu bleiben!“ Sie war sehr enttäuscht, als sie mitbekam, dass ihre Idee so neu nicht ist. Gestern war es ihrem Freund Jan aber doch ein bisschen zu viel. „Das glaubt ihr mir nicht!“, hatte Melanie aufgeregt verkündet. „Ich habe heute erfahren, dass man mit dem Handy Fotos machen kann! Stellt euch das vor! Ist die moderne Technik nicht wunderbar?“ Jan hielt es nicht mehr aus. „Melanie!“ rief er aus, „Wir haben nicht das Jahr 1999! Manchmal glaube ich, du lebst hinter dem Mond …”",
		avatarURL	: "https://www.dw.com/image/19084974_302.png",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/22A5541E_2.mp3"
	},
	{
		title		: "Lieber den Spatz in der Hand als die Taube auf dem Dach",
		text		: "Träume und Wünsche hat jeder. Wenn Menschen zum Beispiel nicht den Traum gehabt hätten, wie die Vögel zu fliegen, wäre das Flugzeug nie erfunden worden. Aber manche Träume sollte man nicht um jeden Preis verfolgen.\n\nLauras Traum war es schon immer, ein Haus mit Garten zu haben. 20 Jahre lang legte sie ihr Geld in Aktien an, um sich ein Haus leisten zu können. Über die Jahre kam eine schöne Summe zusammen, und Laura studierte bereits die Immobilienangebote in der Zeitung und im Internet. Leider hatte sie nicht mit der Finanzkrise gerechnet. Innerhalb von wenigen Wochen war ihr gesamtes Vermögen auf die Hälfte zusammengeschrumpft. Laura war verzweifelt. Aus der Traum vom eigenen Haus mit Garten! Da bekam sie einen Anruf von ihrer Tante Gertrude. „Liebe Laura“, sagte sie am Telefon, „ich weiß, wie traurig du bist wegen der Sache mit dem Haus. Ich möchte dir einen Vorschlag machen. Wie du weißt, ziehe ich bald ins Altersheim. Ich biete dir meine kleine Wohnung in der Altstadt an. Sie ist nicht besonders groß, aber dafür bist du im schönsten Teil der Stadt, und es ist ein riesiger Park in der Nähe, wo du spazieren gehen kannst. Finanziell könnten wir uns bestimmt einigen.“ Da musste Laura nicht lange überlegen. „Ich möchte dein Angebot annehmen“, antwortete sie, „denn wenn ich warte, bis ich wieder genug Geld habe, muss auch ich ins Altersheim. Und wie sagt man so schön? Besser den Spatz in der Hand als die Taube auf dem Dach.“",
		avatarURL	: "https://www.dw.com/image/19084994_302.png",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/79B4B38D_2.mp3"
	},
	{
		title		: "Über den eigenen Schatten springen",
		text		: "Nur wenigen gelingt es, sich von ihrem eigenen Schatten zu lösen: Lucky Luke zum Beispiel schießt schneller als er und Peter Pan sucht ihn. Aber wie schafft man es, über seinen eigenen Schatten zu springen?\n\nGleich ist es 20 Uhr. Der Theatersaal ist voll, das Stück ist ausverkauft. Jonas hat gleich seinen ersten Auftritt. Sie spielen „Wilhelm Tell“, und Jonas hat die Hauptrolle. Dabei stand er noch nie auf einer Bühne. Er hat sich bisher nie getraut, als Schauspieler im Theater aufzutreten, weil er immer so schrecklich aufgeregt ist. Er ist sogar aufgeregt, wenn er an Weihnachten seinen Großeltern ein Gedicht aufsagt. Und jetzt soll er vor hunderten fremden Leuten eine Stunde lang auf der Bühne stehen? Jonas wischt sich den Schweiß von der Stirn. Er zittert am ganzen Körper. Seine Schauspielkollegin Lisa kommt zu ihm. „Ist alles in Ordnung?“, fragt sie. „Nein“, sagt Jonas sichtlich nervös, „ich kann das nicht. Ich gehe nach Hause. Ich bin einfach zu aufgeregt. Schauspielen ist nicht das Richtige für mich.“ Lisa schüttelt den Kopf: „Das ist doch Quatsch. Du kannst das, du musst nur endlich mal über deinen eigenen Schatten springen!“ Jonas nickt. Lisa hat recht. Er muss sich endlich einmal überwinden. Jonas atmet tief durch. Dann geht er entschlossen auf die Bühne. Jetzt muss er für eine Stunde ein Held sein – eine Stunde lang Wilhelm Tell sein!",
		avatarURL	: "https://www.dw.com/image/19185286_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/F7DB628D_2.mp3"
	},
	{
		title		: "Schwein haben",
		text		: "Das Schwein hat es nicht leicht. In vielen Kulturen gilt es als unrein und faul. Will man jemanden beleidigen, bezeichnet man ihn schon mal als „Schwein“. Aber wenn jemand „Schwein hat“, ist das ein Grund zur Freude.\n\nAlfred gehört zu den Menschen, die immer den Kick suchen. Er braucht Abenteuer und Aufregung, weil er sich sonst schnell langweilt. Dazu passt auch sein Hobby: das Glücksspiel. Ob Sportwetten oder Roulette, Alfred liebt es, bis zum Schluss dem Ergebnis entgegenzufiebern. Seine Frau streitet sich deswegen regelmäßig mit ihm und ist langsam mit ihrer Geduld am Ende. Sie glaubt, dass Alfred bisher nur Glück gehabt hat und befürchtet, dass er irgendwann sein ganzes Geld verlieren wird. Alfred ist anderer Meinung. Er glaubt, dass er einfach ein guter Spieler ist. Neulich kommt&nbsp;er total aufgeregt nach Hause und ruft: „Barbara, stell dir vor, ich hatte heute beim Roulette fast alles verloren. Aber ich habe einfach weitergemacht und habe jetzt das Doppelte meines Einsatzes gewonnen!“ Alfreds Frau greift sich an den Kopf. „Alfred, du hast wieder mal Schwein gehabt!“ stöhnt sie genervt. „Aber das war jetzt das letzte Mal! Ich verbiete dir, jemals wieder ins Casino zu gehen. Denn wenn dich das Glück irgendwann im Stich lässt, trenne ich mich von dir.“ Ob Alfred verstanden hat, dass er schon wieder Schwein hatte? Eine letzte Chance bekommt man nicht so oft.",
		avatarURL	: "https://www.dw.com/image/19084987_302.png",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/AB262FAF_2.mp3"
	},
	{
		title		: "Seinen Senf dazugeben",
		text		: "Ob Bratwurst, Weißwurst oder Frikadelle: Manche Speisen schmecken mit Senf einfach besser. Aber man kann Senf auch in einer Diskussion oder bei einem Streit einsetzen. Und darüber freuen sich die wenigsten.\n\nEigentlich wollen Tanja, Hans und Carmen einen netten Nachmittag bei Kaffee und Kuchen verbringen, aber es kommt anders: Tanja und ihr Freund Hans fangen mal wieder einen Streit an. Hans findet es doof, dass Tanja die meiste Zeit am Computer verbringt, während er sich um den Haushalt kümmern muss. „Also, wenn ich nicht putzen würde, würden wir im Dreck untergehen!“, sagt Hans. „Das stimmt doch gar nicht“, erwidert Tanja. „Ich putze doch! Wenn deine Freunde nicht dauernd Dreck machen würden, hätten wir das Problem nicht.“ Während die zwei streiten, sitzt Carmen daneben und versucht, ruhig zu bleiben. Als die beiden nach zehn Minuten immer noch streiten, verliert sie die Geduld: „Also, ich möchte mich ja nicht einmischen …“, sagt sie, „aber wie wäre es, wenn ihr einen Putzplan aufstellt? Würde das die Sache nicht einfacher machen?“ Tanja und Hans schauen sie genervt an. „Musst du wirklich immer zu allem deinen Senf dazugeben“, sagt Tanja, „das geht dich nun wirklich nichts an!“",
		avatarURL	: "https://www.dw.com/image/19035602_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/43ADE08C_2.mp3"
	},
	{
		title		: "Mit jemandem ist nicht gut Kirschen essen",
		text		: "Kirschen sind lecker. Doch man sollte aufpassen, mit wem man sie isst. Denn manche Leute sind so unfreundlich, dass sie einem die Wörter wie Kerne ins Gesicht spucken. Mit ihnen ist eben nicht gut Kirschen essen.\n\nMax ist mit seinem Kollegen auf dem Weg ins Büro. Heute wird sich ihr neuer Chef vorstellen. Als sie an ihrem Schreibtisch sitzen, kommt der neue Chef schon zur Tür herein. „Sie sind beide zwei Minuten zu spät. In Zukunft wird es das nicht mehr geben!“, ruft er. Max und sein Kollege stehen sofort auf. Der Chef ruft weiter: „Solange ich Ihr Boss bin, werden Sie mehr und härter arbeiten müssen. Sie werden oft erst spätabends nach Hause kommen. Und bei mir werden Fehler sofort bestraft. Haben Sie das verstanden?“ Max und sein Kollege nicken. Der Chef will gehen. „Warten Sie! Sollen wir uns nicht erst mal vorstellen?“, sagt Max. „Sie sollen nicht reden, Sie sollen arbeiten!“, brüllt der Chef und geht aus dem Zimmer. „Oh je, mit dem ist aber nicht gut Kirschen essen“, seufzt der Kollege. Max seufzt auch. Die nächsten Jahre werden wohl lang und schwer werden.",
		avatarURL	: "https://www.dw.com/image/19185264_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/D4E44E90_2.mp3"
	},
	{
		title		: "In der Not frisst der Teufel Fliegen",
		text		: "Was isst eigentlich der Teufel den ganzen Tag? So genau weiß das niemand. Vielleicht ist es aber beruhigend zu wissen, dass er nicht alles frisst, was ihm über den Weg läuft. Zumindest nicht freiwillig.\n\nDer große Tag ist da! Kathrin steht um 6 Uhr morgens auf, um sich frisch zu machen und zu ihrer Freundin Lara zu fahren, die heute heiraten wird. Doch wie so oft, wenn es schnell gehen muss, geht etwas schief. Als Kathrin sich das schöne, neue, hellblaue Kleid anziehen will, stellt sie fest: Der Reißverschluss ist kaputt. Ausgerechnet heute! Was tun? Wo bekommt man an einem Sonntagmorgen ein passendes Kleid her? Kathrin hat eine Idee. Sie klingelt ihre Schwester aus dem Bett. „Katja, du musst mir helfen! Ich brauche das Sommerkleid, das du letztes Jahr so oft anhattest“, sagt sie. Katja ist erstaunt: „Du meinst das Kleid, über das du dich dauernd lustig gemacht hast, weil mein Hintern darin so dick aussah?“ „Äh, ja, genau das! Das musst du mir für heute ausleihen. Lara heiratet und der Reißverschluss meines Kleides ist kaputt. Ich habe keine Wahl. Ich brauche ein Kleid.“ „Na klar kannst du es dir ausleihen“, kichert Katja, „in der Not frisst der Teufel Fliegen. Nicht wahr?“",
		avatarURL	: "https://www.dw.com/image/19084972_302.png",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/0C9E8A90_2.mp3"
	},
	{
		title		: "Einen Ohrwurm haben",
		text		: "Einen Ohrwurm haben? Das klingt nach einer ganz fiesen Krankheit. Doch ein Ohrwurm ist zum Glück kein Tier, das einem im Ohr herumkriecht, sondern ein Lied. Das ist zwar nicht gefährlich, kann aber ziemlich nervig sein.\n\nThomas lässt sich gerne von Musik wecken. Am liebsten hört er Pop-Musik aus den 60ern und 70er. Deshalb hat er auch einen Oldie-Sender auf seinem Radio-Wecker eingestellt. Heute Morgen spielt er „Yellow Submarine“ von den Beatles. Gut gelaunt steht Thomas auf und summt die Melodie mit. Unter der Dusche pfeift er sie. Auf dem Weg zur Arbeit singt er sie. Und auch als er im Büro sitzt, hat er die Musik noch im Kopf. Er kann sich gar nicht auf die Arbeit konzentrieren. „Ich habe schon den ganzen Morgen einen Ohrwurm“, sagt er zu seinem Kollegen. „Ich weiß. Du summst ja die ganze Zeit dieses Lied. Deinetwegen habe ich jetzt auch einen“, antwortet der Kollege. Thomas will, dass der Ohrwurm verschwindet. Er singt einen anderen Song, „Dancing Queen“ von ABBA. Vielleicht hilft das. Und tatsächlich: An „Yellow Submarine“ denkt Thomas nicht mehr. Dafür hat er jetzt einen anderen Ohrwurm. Aber als Thomas abends nach Hause kommt, sind die Beatles wieder da. Im Bett greift er zum Wecker und ändert den Sender. Er will nicht schon wieder den ganzen Tag lang einen Ohrwurm haben. Thomas liegt im Bett und kann nicht schlafen. Er pfeift immer noch „Yellow Submarine“… Verdammter Ohrwurm!",
		avatarURL	: "https://www.dw.com/image/19185265_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/70F96ED4_2.mp3"
	},
	{
		title		: "Eine Extrawurst bekommen",
		text		: "Die Deutschen sind ein Volk von Wurstessern. Und zwar so sehr, dass sich hier sogar Vegetarier über eine Wurst freuen können – zumindest, wenn es sich redensartlich um eine Extrawurst handelt.\n\nTim ist ein guter Fußballspieler – finden seine Eltern. Sie sind davon überzeugt, dass er später einmal Profi werden kann. Deswegen fahren sie ihn viermal die Woche zum Training und erlauben ihm, jede freie Minute mit seinen Freunden Fußball zu spielen. Letzte Woche musste Tim nicht mal seine Hausaufgaben zu Ende machen: Seine Eltern haben der Schule einfach eine Entschuldigung geschrieben. Tims Schwestern Hannah und Lara ärgern sich schon lange darüber, dass ihr Bruder ständig eine Sonderbehandlung bekommt. Aber heute sind sie so richtig wütend: Beim Abendessen haben ihnen die Eltern gerade erzählt, dass sie nächstes Wochenende alle zu Tante Gisela fahren werden. Ausgerechnet zu Tante Gisela, die Kinder doch sowieso nicht leiden kann! Das Schlimmste aber ist: Tim muss nicht mitkommen. Er darf zu seinem Freund Carl, um für das nächste Spiel zu trainieren. Hannah und Lara springen auf: „Das ist unfair!“ rufen sie fast gleichzeitig. „Tim bekommt immer eine Extrawurst!“ Ihre Eltern gucken erstaunt. „Wieso? Ihr mögt Fußball doch gar nicht“, sagt die Mutter. Die Mädchen stöhnen. Nichts hat die Mutter verstanden, gar nichts!",
		avatarURL	: "https://www.dw.com/image/19185263_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/CDEB0E4D_2.mp3"
	},
	{
		title		: "Jemandem Löcher in den Bauch fragen",
		text		: "Ein Loch im Bauch – da denkt man doch gleich an Mord und Totschlag. Zum Glück steckt meist etwas ganz Harmloses dahinter. Was aber nicht heißt, dass die betroffenen Menschen sich darüber freuen würden.\n\nKinder wollen alles wissen. Doch die kleine Anna ist etwas zu neugierig. Sie stellt ununterbrochen Fragen. „Mama, wo wohnt die Oma?“, fragt Anna. „In Köln“, antwortet die Mutter, die eigentlich versucht zu arbeiten. Aber Anna fragt weiter: „Wo liegt das?“ „In Nordrhein-Westfalen“, sagt die Mutter geduldig. „Ist das in der Nähe von Berlin?“ „Nein, Berlin liegt im Osten von Deutschland und Köln im Westen.“ Und die kleine Anna fragt immer weiter: „Warum wohnt die Oma in Köln?“ „Sie wurde dort geboren und lebt schon ihr ganzes Leben dort“, erklärt die Mutter schon leicht genervt. „Ja, aber warum wurde sie dort geboren?“, fragt Anna. „Weil die Eltern von deiner Oma auch in Köln gelebt haben“, sagt die Mutter. „Und warum haben sie nicht in Berlin gelebt?“, fragt Anna. Jetzt hat die Mutter genug. Sie kann sich bei der ganzen Fragerei gar nicht konzentrieren. „Hör auf, mir Löcher in den Bauch zu fragen! Ich muss arbeiten“, sagt sie streng. „Warum stört dich das?“, fragt Anna, „was arbeitest du?“ Die Mutter seufzt. Die kleine Anna ist nicht zu stoppen. Sie ist einfach zu neugierig.",
		avatarURL	: "https://www.dw.com/image/19185285_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/F7F07546_2.mp3"
	},
	{
		title		: "Über den Tellerrand schauen",
		text		: "Die meisten Menschen fühlen sich dort wohl, wo sie sich auskennen. Doch wer sich traut, über den Tellerrand zu schauen, kann einiges entdecken – und zwar nicht einen Becher oder Besteck, sondern die ganze Welt.\n\nMona hat endlich das Abitur gemacht. Die große Frage lautet: Was macht sie nun? „Geh doch nach Afrika und hilf dort bei einem Freiwilligenprojekt“, rät ihr ihre beste Freundin. „Mach ein Praktikum in den USA oder in Kanada!“, sagt ihr Vater. „Geh ein Jahr lang nach Frankreich und arbeite dort als Au-Pair“, empfiehlt ihr Bruder. „Mach eine Weltreise!“, ruft die Tante. Aber Mona will das alles nicht. „Ich möchte nicht weg. Ich möchte zuhause bleiben“, sagt sie. Sie liebt Tiere und arbeitet zurzeit manchmal im Tierheim. Das möchte sie weiterhin machen. „Mach eine Ausbildung zur Bäckerin!“, rät ihr ihre beste Freundin. „Studiere Wirtschaftswissenschaften“, sagt ihr Vater. „Werde Automechanikerin“, empfiehlt ihr Bruder. „Geh in die Politik“, ruft die Tante. „Ich will das alles nicht“, schreit Mona, „ich will nichts Neues. Ich will das machen, was ich kenne, und an dem Ort bleiben, den ich kenne.“ Alle anderen schütteln den Kopf. „Du solltest mal über den Tellerrand schauen“, sagen sie. „Es gibt doch so viel zu entdecken auf der Welt.“ Aber Mona bleibt stur.",
		avatarURL	: "https://www.dw.com/image/19185288_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/E10AB5B8_2.mp3"
	},
	{
		title		: "Ein Tropfen auf dem heißen Stein",
		text		: "Was nützt es, wenn man einen Tropfen Wasser auf einen heißen Stein fallen lässt? Nicht viel. Der Tropfen verdampft sofort. Um einen messbaren Effekt zu erzielen, braucht es schon deutlich mehr.\n\nMaria ist richtig sauer. Morgen kommen ihre Eltern zu Besuch, und ihre Wohnung ist so unordentlich wie noch nie. Max sollte eigentlich aufräumen, während Maria bei der Arbeit war. Doch er hat nur auf der Couch gesessen und ferngesehen. Maria schimpft: „Sieh dir mal das Chaos an!“ Auf dem Fußboden liegen Kleidungsstücke, leere Flaschen, alte Zeitungen und Papiere. In der Spüle stapeln sich die dreckigen Teller und Gläser. Sogar ein alter, brauner Apfel liegt dazwischen. Und überall ist Staub. „Hast du den ganzen Tag vor dem Fernseher gesessen? Wieso hast du nicht aufgeräumt?“, ruft Maria. Max weiß gar nicht, warum Maria so wütend ist. „Ich habe doch die Bücher vom Boden aufgehoben und ins Regal gestellt“, sagt er. „Na, das war aber auch nur ein Tropfen auf den heißen Stein!“, antwortet Maria und blickt sich um. Sie macht den Fernseher aus. Bis die Wohnung nicht sauber ist, wird der Fernseher nicht mehr angemacht. Darauf kann Max sich verlassen.",
		avatarURL	: "https://www.dw.com/image/19185287_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/73057BAE_2.mp3"
	},
	{
		title		: "Das schwarze Schaf sein",
		text		: "Eine Herde voller weißer Schafe – eines sieht aus wie das andere. Und mittendrin steht ein schwarzes Schaf. Dieses Schaf fällt auf – leider nicht unbedingt im positiven Sinne. So sehen es zumindest die weißen Schafe.\n\nDie beiden älteren Frauen Bertha und Hilde treffen sich zu Kaffee und Kuchen, um zu reden und Neuigkeiten auszutauschen. Bertha erzählt von ihren drei Enkeln: „Paul ist der Älteste. Er ist Anwalt, ist verheiratet und hat drei Kinder. Patrick ist der Zweitälteste und ist Arzt geworden wie seine Eltern. Er arbeitet zu viel, um sich um eine Familie kümmern zu können. Aber Tom, der Jüngste, der macht uns vielleicht Sorgen!“ „Wieso denn?“, fragt Hilde. „Er wollte nicht studieren“, antwortet Bertha, „er arbeitet jetzt als Verkäufer in einem Kiosk und er raucht. Er hat sich eins von diesen Tattoos in die Haut gebrannt. Ja, Tom hat sogar ein Kind, ohne verheiratet zu sein. Aber weißt du, was das Schlimmste ist...“ „Was denn?“, fragt Hilde neugierig. „Letzten Monat war er sogar im Gefängnis, weil er eine Geldbuße nicht bezahlen wollte“, erzählt Bertha. „Ist nicht wahr!“ Hilde schüttelt erstaunt den Kopf. Bertha zuckt mit den Schultern. „Tom war schon immer das schwarze Schaf der Familie“, sagt sie, „dabei ist er eigentlich so ein lieber Junge.“",
		avatarURL	: "https://www.dw.com/image/19395305_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/BC11BACF_2.mp3"
	},
	{
		title		: "Jemandem die Suppe versalzen",
		text		: "Eine Suppe kann sehr lecker sein, besonders mit der richtigen Menge Salz. Tut man aber zu viel davon rein, ist sie nicht mehr genießbar. Wer würde sich nicht ärgern, wenn ihm jemand heimlich die Suppe versalzen würde?\n\nLena hat eine neue Kollegin. Sie heißt Julia, ist sehr hübsch und sehr elegant. Darum ist Lena ein bisschen eifersüchtig auf sie. Und das Schlimmste ist: Beide haben sich in denselben Mann verliebt, in Bastian aus der Marketing-Abteilung. Schon seit einiger Zeit versuchen beide, ihm näherzukommen. Und gestern hatte Julia tatsächlich Erfolg: Für nächsten Dienstag hat sie sich mit Bastian verabredet. Doch leider erfährt auch Lena davon – und die ist sofort alarmiert. „Na warte, dir werde ich die Suppe schon noch versalzen“, denkt sie und geht zu ihrem Chef. Für ihre wichtige Telefonkonferenz am Dienstagabend mit den Kollegen aus den USA bräuchte sie unbedingt Julias Fachwissen, erklärt sie ihm. Ihr Chef stimmt zu, Julias Protest ist erfolglos. Lena ist selbst überrascht, dass sie so gemein sein kann. Doch wenn es um die Liebe geht, ist alles erlaubt, denkt sie sich.",
		avatarURL	: "https://www.dw.com/image/19215031_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/E91C8CF3_2.mp3"
	},
	{
		title		: "Unter einer Decke stecken",
		text		: "Unter einer Decke ist es warm und gemütlich. Was darunter passiert, kann man von außen nicht sehen. Es bleibt geheim. Doch was bedeutet es, wenn mehrere Personen unter einer Decke stecken? Oft nichts Gutes …\n\nIn einem kleinen Dorf wurde ein Koffer mit sehr viel Geld gestohlen. Zwei Polizisten ermitteln und befragen alle Einwohner des Ortes, aber keiner hat etwas gesehen. Und niemand weiß von dem Koffer. Doch fast alle haben vor kurzer Zeit viel Geld ausgegeben. Einer hat sich ein neues Auto gekauft. Ein anderer hat den Garten umbauen lassen. Ein Dritter hat sich einen riesigen Fernseher gekauft. Die beiden Polizisten finden das sehr verdächtig. „Wie kann es sein, dass keiner etwas von dem Geldkoffer weiß? Wieso verrät keiner, wer den Koffer gestohlen hat?“, fragt der Polizist. „Die stecken alle unter einer Decke“, sagt sein Kollege. „Du meinst, das ganze Dorf steckt unter einer Decke?“, fragt der erste Polizist nach. Der Kollege nickt. „Das ist ein ganz großes Verbrechen!“, da ist er sich sicher. Die Polizisten stöhnen. Das klingt nach sehr viel Arbeit.",
		avatarURL	: "https://www.dw.com/image/19395306_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/7C220106_2.mp3"
	},
	{
		title		: "Ein dickes Fell haben",
		text		: "Viele Tiere haben ein dickes Fell. Es hilft ihnen, starke Kälte und Wind zu ertragen. Auch manche Menschen können ein dickes Fell haben, um sich zu schützen. Und dafür brauchen sie nicht mal Haare.\n\nJan und Mia waren gestern Abend auf einer Party. Am nächsten Morgen sprechen sie darüber, was auf der Party passiert ist. „Du warst gestern gemein zu Eva. Ich dachte, du magst sie“, sagt Mia. „War ich gemein? Wie kommst du darauf?“, fragt Jan. „Du hast sie beleidigt. Du hast gesagt, dass sie dicker geworden ist. Und du hast ihr gesagt, dass sie tanzt wie ein betrunkener Bär“, antwortet Mia. „Das macht der Eva nichts aus“, sagt Jan sicher, „das findet die nicht schlimm. Eva hat ein dickes Fell. Und das muss man auch haben, wenn man mit mir befreundet ist. Ich sage halt, was ich denke.“ Mia schüttelt den Kopf: „Also, ich fand das echt nicht in Ordnung. Das hat auch mit Respekt zu tun. Du hast dich nicht richtig benommen!“, sagt sie. Jan guckt sie beleidigt an: „Dann lass mich doch in Ruhe, wenn du mich nicht magst“, schimpft er. Mia lacht. „Du hast anscheinend kein dickes Fell, wenn du auf ein bisschen Kritik sofort beleidigt reagierst!“, sagt sie.",
		avatarURL	: "https://www.dw.com/image/19270836_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/FF8556DE_2.mp3"
	},
	{
		title		: "Eine Doktorarbeit aus etwas machen",
		text		: "Es gibt Menschen, bei denen selbst kleine Arbeiten endlos dauern. Sie denken über jede Kleinigkeit lange nach, entscheiden sich oft um und beginnen wieder von vorn. Für andere kann das ziemlich nervig sein.\n\nWerner hat ein sehr schönes Foto von einem Sonnenuntergang gemacht. Das möchte er jetzt in seiner Wohnung aufhängen. Er fragt seine Frau Hilde: „In welches Zimmer soll ich das Bild hängen?“ Hilde zuckt mit den Schultern. „Das ist egal. Häng es irgendwo hin“, sagt sie. „Ins Wohnzimmer? Ins Schlafzimmer? Ins Bad?“, fragt Werner. „Das ist wirklich ganz egal“, antwortet Hilde. Werner entscheidet sich für das Wohnzimmer. Über dem Fernseher sieht das Bild bestimmt gut aus. Er nimmt den Nagel und den Hammer und will es aufhängen. „Ist es so gut? Oder besser ein bisschen weiter rechts?“, fragt er seine Frau. „Hängt das Bild schief? Soll ich es höher hängen? Oder besser tiefer? Oder doch in die Küche?“ „Mein Gott!“, ruft Hilde genervt, „mach doch keine Doktorarbeit daraus! Häng es einfach irgendwo auf!“ Werner geht beleidigt in die Küche und hängt das Bild neben den Kühlschrank. Hilde kommt in den Raum und betrachtet es. „Im Wohnzimmer hätte das Bild besser ausgesehen“, sagt sie. Werner schüttelt verzweifelt den Kopf.",
		avatarURL	: "https://www.dw.com/image/19270857_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/F7246DCB_2.mp3"
	},
	{
		title		: "In einem Boot sitzen",
		text		: "Wer war nicht schon einmal in einer schwierigen Lage? Gut, wenn man dann nicht alleine ist. Denn wenn die anderen dieselben Ziele und Interessen haben, findet man zusammen bestimmt eine Lösung.\n\nAlex und Daniel haben nächste Woche eine wichtige Prüfung. Wenn sie diese Prüfung nicht bestehen, dürfen sie nicht weiter an der Universität bleiben. Und der Professor ist nicht sehr rücksichtsvoll: Er macht die Prüfungen gerne sehr schwer, damit viele Studenten sie nicht bestehen. Alex und Daniel sind deshalb sehr nervös, sie wollen die Prüfung unbedingt schaffen. „Sollen wir zusammen lernen?“, fragt Alex. „Besser nicht“, antwortet Daniel, „ich lerne lieber alleine. Dann kann ich mich besser konzentrieren.“ Aber Alex will nicht alleine lernen. Er sagt: „Lass uns zusammenarbeiten! Wir sitzen doch in einem Boot. Wir können bestimmt voneinander lernen.“ Daniel denkt nach. „Vielleicht hast du recht“, sagt er, „zu zweit sieht man mehr als allein.“ Und tatsächlich: Die beiden lernen viel voneinander. Hoffentlich reicht das auch für die Prüfung!",
		avatarURL	: "https://www.dw.com/image/19270868_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/5CC46FDF_2.mp3"
	},
	{
		title		: "Eins auf den Deckel bekommen",
		text		: "Der Angestellte vom Chef, das Kind von seinen Eltern, der Schüler vom Lehrer – sie alle können schon mal eins auf den Hut, also den Deckel bekommen. Zwar nicht im wörtlichen Sinne, aber unangenehm ist es trotzdem.\n\nKilian und Finn wissen genau, was sie später einmal werden wollen: Profifußballer. Deswegen üben sie jeden Tag im Hof und schießen gegen die Hauswand. Ihre Mutter hat ihnen zwar schon oft gesagt, dass sie das nicht tun sollen, aber Fußball ist den beiden wichtiger. Und dann passiert es: Finn passt nicht auf und schießt den Ball zu hoch. Er fliegt gegen das Fenster, und die Scheibe geht kaputt. Finns Mutter läuft heraus. „Finn! Komm sofort her“, ruft sie. Finn gehorcht und geht ins Haus. Kilian wartet draußen. Nach einer halben Stunde kommt Finn wieder heraus. „Hast du eins auf den Deckel bekommen?“, fragt Kilian. Finn nickt. „Sie war sehr sauer. Ich bekomme im nächsten Monat kein Taschengeld. Und ich darf zwei Wochen kein Fußball mehr spielen“, sagt er. „Machst du es trotzdem?“, fragt Kilian. „Klar!“, sagt Finn, „sonst werde ich doch kein guter Fußballspieler. Mir egal, wenn ich ständig eins auf den Deckel bekomme. Hauptsache, ich spiele später beim FC Bayern!“ Beide Jungen holen sich den Ball und spielen weiter.",
		avatarURL	: "https://www.dw.com/image/19270874_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/062EDC1C_2.mp3"
	},
	{
		title		: "Der Esel nennt sich immer zuerst",
		text		: "Wenn man von sich selbst und anderen Personen redet, dann nennt man als höflicher Mensch die anderen Personen zuerst. Macht man das nicht, muss man damit rechnen, als Esel bezeichnet zu werden.\n\nDer kleine Fabian hat zum ersten Mal bei einem Freund übernachtet. Am nächsten Tag erzählt er seinem Vater, was sie alles gemacht haben. „Das war ein toller Abend. Wir hatten super viel Spaß. Ich und Georg haben …“ Doch der Vater unterbricht ihn: „Stopp! Der Esel nennt sich immer zuerst!“ Fabian ist verwirrt. „Du sollst dich nicht zuerst nennen, wenn du von mehreren Personen sprichst“, erklärt der Vater. „Das ist unhöflich. Das macht man nicht.“ Fabian ist aber viel zu aufgeregt, um auf Höflichkeit zu achten. Er erzählt weiter: „Ich und Georg haben uns mit Kissen geschlagen und sind durch das Haus gerannt.“ „Was habe ich dir gerade gesagt?“, fragt der Vater ernst. „Und dann haben ich und Georg einen Film geguckt“, sagt Fabian. „Sag nicht immer ‚ich und Georg‘, sondern ‚Georg und ich‘!“, ruft der Vater böse. „Der Esel …“ Doch jetzt unterbricht Fabian seinen Vater: „Du bist ein Esel“, ruft er wütend. Oh je, das gibt Ärger! So bald darf Fabian wohl nicht wieder bei einem Freund übernachten.",
		avatarURL	: "https://www.dw.com/image/19271026_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/78B8E63A_2.mp3"
	},
	{
		title		: "Den Gürtel enger schnallen",
		text		: "Wer kennt das nicht: Man hat zugenommen und muss den Gürtel ganz weit machen. Um den Gürtel enger schnallen zu können, muss man weniger essen. Bei einer deutschen Redensart muss man aber noch auf viel mehr verzichten.\n\nBjörn sitzt vor seinem Schreibtisch. Dort liegen viele Rechnungen. Sein Geschäft läuft zurzeit nicht gut und sein Konto ist fast leer. Er weiß nicht, wie er die nächsten Monate überstehen soll. Sein Freund hat ihm schon gesagt, dass er den Gürtel eben enger schnallen müsste. Aber Björn will das nicht glauben – bis er auf seine hohe Stromrechnung schaut. Vielleicht sollte er doch seinen Gefrierschrank verkaufen und weniger Fernsehgucken? Wofür hat er noch Geld ausgegeben? Björn sieht sich seine Rechnungen an. Hundert Euro für Bücher, 50 Euro fürs Kino, und allein 300 Euro hat Björn für Wein bezahlt. Er bekommt sechs Zeitschriften, die 80 Euro im Monat kosten. Und er zahlt 60 Euro im Monat für ein Fitnessstudio, in das er zu selten geht. „Ich gebe echt viel Geld aus“, stellt Björn staunend fest. Aber das sind auch alles Dinge, die ihn glücklich machen. Und auf die soll er in Zukunft verzichten? „Das muss ich wohl“, denkt Björn, „ich muss tatsächlich den Gürtel enger schnallen.“ Er bestellt sofort die Zeitschriften ab und kündigt das Fitnessstudio. Er nimmt sich vor, in nächster Zeit nicht ins Kino zu gehen und weniger Wein zu trinken. Dann wird er es schon irgendwie schaffen.",
		avatarURL	: "https://www.dw.com/image/19270841_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/99908650_2.mp3"
	},
	{
		title		: "Viele Köche verderben den Brei",
		text		: "Alleine arbeitet man manchmal am besten. Denn wenn viele Menschen mit unterschiedlichen Meinungen und Methoden zusammen etwas machen wollen, kann das zu Schwierigkeiten führen. Das sagt auch ein deutsches Sprichwort.\n\nKatie hat sich einen neuen Kleiderschrank gekauft. Er ist sehr groß, und es ist nicht leicht, ihn aufzubauen. Zum Glück hat Katie Freundinnen, die ihr dabei helfen wollen. Sie stehen zu viert vor dem Schrank, Katie liest die Anleitung. „Ich brauche keine Anleitung“, sagt Julia und will gleich Löcher in die Rückwand bohren. „Moment, wir fangen mit den Türen an“, ruft Anne und nimmt die Türen in die Hand. „Wir müssen erst diese Bretter hier zusammenschrauben“, sagt Marie und greift nach den Schrauben. „Warte!“, ruft Katie, „wenn du schon die Bretter zusammenschraubst und Anne die Türen so herum hält und Marie an dieser Stelle bohrt, dann passt das alles zum Schluss nicht zusammen.“ Aber die Frauen machen so weiter, wie sie begonnen haben. Keine achtet darauf, was die anderen tun. „Ich sollte den Schrank doch alleine aufbauen!“, denkt Katie, „viele Köche verderben den Brei.“ Sie atmet tief ein. „Geht alle raus!“, schreit sie, „ihr macht den Schrank noch kaputt!“ Julia, Anne und Marie gehen beleidigt nach draußen. „Die ist ja undankbar. Wir helfen ihr, und sie schreit uns an“, sagen sie und schütteln den Kopf.",
		avatarURL	: "https://www.dw.com/image/19270880_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/2D3B9AB2_2.mp3"
	},
	{
		title		: "Den Faden verlieren",
		text		: "Wer etwas verliert und es wiederhaben will, muss suchen – in dieser Ecke oder in jener. Den redensartlichen Faden findet man dort aber nicht. Dazu muss man schon in die Tiefe seines eigenen Geistes eindringen.\n\nPeter ist Schriftsteller, ein erfolgreicher sogar. Sein letztes Buch war sofort ausverkauft. Jetzt muss er der Presse ein Interview geben. Viele Reporter sitzen vor ihm und blicken ihn an. „Worum wird es in Ihrem nächsten Buch gehen?“, fragt ein Journalist. „Das nächste Buch wird ein Krimi“, erzählt Peter, „Im Mittelpunkt steht eine Frau, die alleine im Wald lebt. Sie hat seit Jahren keinen Menschen mehr gesehen. Doch dann findet sie in der Erde viel Geld und …“ Peter hört plötzlich auf zu reden. Eine schöne Frau hat den Raum betreten und setzt sich zu den Reportern. Peter blickt sie an. Sie kommt ihm bekannt vor. Sie lächelt ihn an. Peter lächelt zurück. Dann fällt ihm ein, dass er gerade über sein neues Buch gesprochen hat. Was hat er schon gesagt? Wo hat er aufgehört zu reden? Peter weiß nicht mehr, welchen Teil seiner Geschichte er schon erzählt hat. „Entschuldigung, ich habe den Faden verloren“, sagt er. „Die Frau im Wald hat Geld gefunden“, ruft ein Reporter. Peter erinnert sich wieder. „Richtig. Dann findet sie einen toten Mann“, sagt Peter und lächelt der hübschen Frau zu. Sie lächelt zurück. Vielleicht sollte Peter besser einen Liebesroman schreiben.",
		avatarURL	: "https://www.dw.com/image/19270875_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/CA34FDD9_2.mp3"
	},
	{
		title		: "Mit den Wölfen heulen",
		text		: "Es ist immer einfach, das zu tun, was die Mehrheit tut. Denn dann muss man nicht nachdenken und keine Verantwortung übernehmen. Als Einziger etwas zu machen, erfordert dagegen Mut und Selbstvertrauen.\n\nFreddie hat eine neue Arbeitsstelle. Erst hat er sich gefreut, aber schnell merkt er, dass die Atmosphäre im Unternehmen schlecht ist. Und er erkennt auch bald, woran das liegt: Die Geschäftsleitung setzt die Mitarbeiter unter Druck, erwartet unbezahlte Überstunden und droht ständig mit Konsequenzen. Aber das Schlimmste ist: Keiner beschwert sich, jeder befolgt die Anweisungen und arbeitet still vor sich hin. Gestern wurde sein Kollege Martin von seinem Chef ins Büro gerufen. Den restlichen Tag über machte Martin dann einen deprimierten Eindruck. Als Freddie ihn fragte, was los sei, klagte er: „Mein Chef hat mir einfach meinen Urlaub nächste Woche gestrichen, obwohl wir doch die Reise schon gebucht haben. Meine Familie und ich haben sich so drauf gefreut.“ Freddie ist empört: „Warum lässt du dir das gefallen? Da musst du dich doch wehren“, ruft er. Doch Martin entgegnet: „Niemand macht so etwas hier, wir wollen schließlich Karriere machen. Man muss eben mit den Wölfen heulen, um erfolgreich zu sein.“ Freddie ist sich sicher: Das wird er ganz bestimmt nicht tun.",
		avatarURL	: "https://www.dw.com/image/19395319_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/1228952C_2.mp3"
	},
	{
		title		: "Das Eis brechen",
		text		: "Es gibt Situationen, in denen es gefährlich ist, wenn das Eis bricht, etwa wenn man auf einem zugefrorenen See steht. Anderswo ist das aber sehr erwünscht. Ein Abend kann dann schon mal viel entspannter verlaufen.\n\nMiriam und Sebastian wollen heiraten. Sie sitzen gerade in einem Restaurant, denn heute sollen sich Miriams Eltern und Sebastian kennenlernen. Miriam ist sehr aufgeregt, weil sie nicht weiß, ob die drei sich mögen werden. Ihre Eltern kommen herein, begrüßen ihre Tochter und schütteln Sebastian die Hand. Alle lächeln freundlich. Es scheint gut zu laufen. Aber dann ist es still. Niemand weiß, was er sagen soll. Alle blicken sich an, aber keiner redet. Die Situation ist unangenehm. Alle vier fühlen sich unwohl. Mittlerweile ist die Stille peinlich. Sebastian hat eine Idee, wie er die Lage retten kann. Er erzählt einen Witz: „Es treffen sich ein Anwalt und ein Arzt. Der Anwalt fragt: ‚Wie geht’s?‘ Der Arzt sagt: ‚Gut, ich kann nicht klagen. Und dir?‘ Da sagt der Anwalt: ‚Schlecht, ich kann nicht klagen‘.“ Sebastian schaut Miriams Eltern an. Die Eltern schauen sich an. Dann lachen sie laut und fangen an zu reden. Das Eis ist gebrochen. Miriams Vater ist nämlich Anwalt und redet jetzt lange über seine Arbeit. Miriam ist erleichtert. Was, wenn ihre Eltern den Witz nicht lustig gefunden hätten? Dann wäre alles nur noch schlimmer geworden.",
		avatarURL	: "https://www.dw.com/image/19270827_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/BB7CF157_2.mp3"
	},
	{
		title		: "Zwei linke Hände haben",
		text		: "Die meisten Menschen sind Rechtshänder. Mit der linken Hand sind sie deshalb oft nicht sehr geschickt. Wie ungeschickt müssen also die Leute sein, die zwei linke Hände haben?\n\nLuisa und Karl ziehen um. „Ich frage Pascal, ob er uns beim Umzug hilft. Aber ich warne dich: Pascal hat zwei linke Hände“, sagt Karl. Und er hat recht: Schon die erste Kiste, die Pascal hochhebt, lässt er fallen. Das ganze Geschirr darin ist kaputt. Auch mit der zweiten Kiste hat er Schwierigkeiten. „Ist nicht so schlimm“, sagt Karl, „vielleicht trägst du besser nichts mehr, sondern baust unseren Schrank auf.“ Pascal beginnt sofort damit. Doch als Karl nach kurzer Zeit zurückkommt, erschrickt er. Die Türen hängen falsch herum am Schrank, auf den Brettern sind dicke Kratzer und sogar der Schraubenzieher und der Hammer sind zerbrochen. „Soll ich mal deinen Fernseher ins Wohnzimmer tragen?“, fragt Pascal. „Auf keinen Fall!“, ruft Karl schnell. „Soll ich Luisas Spiegel holen?“, fragt Pascal. „Bloß nicht!“, schreit Luisa aus dem anderen Zimmer. „Ich glaube, jetzt brauchen wir deine Hilfe nicht mehr. Vielen Dank!“, sagt Karl. Nachdem Pascal die Wohnung verlassen hat, sagt Luisa staunend: „Mein Gott, der hat ja wirklich zwei linke Hände!“",
		avatarURL	: "https://www.dw.com/image/19270823_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/EF5FEFDE_2.mp3"
	},
	{
		title		: "Sich freuen wie ein Schneekönig",
		text		: "Es gibt viele Arten, sich zu freuen. Man kann laut lachen oder schreien. Man kann hüpfen oder rennen. Und manche Menschen hören sich dabei fast so an wie ein Vogel – wie der Zaunkönig, der auch Schneekönig genannt wird.\n\nMoritz ist glücklich. Er fühlt sich richtig gut. Er springt auf dem Weg nach Hause vor Freude in die Höhe und singt dabei laut. Sein Nachbar hört ihn schon von Weitem. Er sieht Moritz’ breites Lächeln und wie er immer wieder in die Luft springt. „Na, du freust dich ja wie ein Schneekönig. Was ist denn passiert?“, fragt der Nachbar. Moritz lacht laut. „Ich habe Vanessa einen Heiratsantrag gemacht. Und sie hat Ja gesagt“, ruft Moritz glücklich. „Das ist ja toll!“, sagt der Nachbar, „herzlichen Glückwunsch.“ – „Und das ist noch gar nicht alles“, ruft Moritz fröhlich, „ich habe auch noch im Lotto gewonnen – fast ein halbe Million Euro. Ist das nicht toll?“ Der Nachbar kann es kaum glauben. „Das gibt es nur selten. Glück im Spiel und in der Liebe haben nur wenige“, sagt er. „Ich habe beides“, sagt Moritz, „und ich weiß nicht, worüber ich mich mehr freue!“ Wenn Vanessa das gehört hätte …",
		avatarURL	: "https://www.dw.com/image/19270869_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/08B1814C_2.mp3"
	},
	{
		title		: "Alles unter einen Hut bringen",
		text		: "Heute tragen nur noch wenige Menschen Hüte. Aber trotzdem wollen viele Leute oft alles unter einen Hut bringen. So stellt man sicher, dass jeder zufrieden ist und alle Arbeiten erledigt sind. Doch das klappt nicht immer.\n\nFamilie Schmidt ist eine große Familie. Wenn der Urlaub geplant wird, hat jeder andere Vorstellungen davon, wie die Reise aussehen soll. Vater Klaus möchte in große Städte fahren und Museen besuchen. Der älteste Sohn will in den Bergen wandern. Seine Schwester würde gerne am Meer Urlaub machen und den ganzen Tag am Strand liegen. Die andere Schwester wünscht sich schon seit Jahren, mal eine große Fahrradtour durch Deutschland zu machen. Und der Jüngste will einen Freizeitpark besuchen, um dort Achterbahn zu fahren. Nur Mutter Birgit ist es egal, wohin die Reise geht. Sie möchte bloß, dass alle glücklich sind. „Es wird nicht leicht, einen Urlaubsort zu finden, mit dem alle zufrieden sind“, sagt Klaus. „Ich weiß“, sagt Birgit, „alle haben so unterschiedliche Wünsche. Wie sollen wir die alle unter einen Hut bringen?“ „Man kann nicht immer alles unter einen Hut bringen“, antwortet Klaus, „manchmal muss man eben das tun, was der Vater sagt!“ Birgit schüttelt den Kopf. Das kommt nicht in Frage. Der Urlaubsplan wird erst noch mal gründlich diskutiert – mit der ganzen Familie!",
		avatarURL	: "https://www.dw.com/image/19270814_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/3130DD39_2.mp3"
	},
	{
		title		: "Unter den Blinden ist der Einäugige König",
		text		: "Einmal König sein – etwas Besseres kann es doch gar nicht geben! Aber Achtung, es kommt immer drauf an, wo und für wen man König ist. Und so könnte es sein, dass man sich gar nicht über den Titel freuen kann.\n\nDie Freunde Hanno und Marcel unterhalten sich. „Ich habe gestern ein Tennisturnier gewonnen“, erzählt Hanno. „Wer hat denn alles mitgemacht?“, fragt Marcel. „Michael, Kai, Rolf und Andreas. Und ich habe gewonnen“, sagt Hanno stolz. „Unter den Blinden ist der Einäugige König“, sagt Marcel. Hanno blickt seinen Kumpel böse an: „Was soll das denn heißen?“ „Die vier sind keine guten Tennisspieler“, erklärt Marcel. Er zählt auf: „Michael hat noch nie vorher in seinem Leben Tennis gespielt. Kai wiegt 25 Kilo zu viel und kann sich kaum bewegen. Rolf ist 30 Jahre älter als du und nicht mehr sehr fit.“ „Und Andreas?“, fragt Hanno. „Andreas ist einfach unsportlich, er kann nichts besonders gut“, antwortet Marcel. „Es ist also nicht sehr schwer, gegen diese vier Gegner im Tennis zu gewinnen. Du solltest mal gegen mich spielen.“ Aber Hanno will nicht gegen Marcel Tennis spielen. Denn gegen Marcel hat er wirklich keine Chance.",
		avatarURL	: "https://www.dw.com/image/19270819_302.jpg",
		mediaURL	: "https://radiodownloaddw-a.akamaihd.net/Events/dwelle/dira/mp3/deutschkurse/dassagtmanso/AD6F00EC_2.mp3"
	}
]