import * as g                           from '../../types/genetics'

export const ABC: g.snapMargin = [] as any;
export const MDL: g.OrganelleType[] = [ "dImage", "rawText" ];
export const DNA: g.gene[] = [
	{
		title		: "Your teacher can open the door, but you must enter by yourself.",
		text		: "Your teacher can open the door, but you must enter by yourself.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-35-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-35-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Better to light a candle than to curse the darkness.",
		text		: "Better to light a candle than to curse the darkness.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-34.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-34.jpg",
		media_C 	: false,
	},
	{
		title		: "Distance tests a horse’s strength. Time reveals a person’s character.",
		text		: "Distance tests a horse’s strength. Time reveals a person’s character.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-33-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-33-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Give me a fish and I eat for a day. Teach me to fish and I eat for a lifetime.",
		text		: "Give me a fish and I eat for a day. Teach me to fish and I eat for a lifetime.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-32.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-32.jpg",
		media_C 	: false,
	},
	{
		title		: "If you plan for one year, plant rice. If you plan for ten years, plant trees, If you  plan for 100 years, educate mankind.",
		text		: "If you plan for one year, plant rice. If you plan for ten years, plant trees, If you  plan for 100 years, educate mankind.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-31-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-31-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "A single conversation with a wise man is worth a month’s study of books.",
		text		: "A single conversation with a wise man is worth a month’s study of books.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-30.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-30.jpg",
		media_C 	: false,
	},
	{
		title		: "When you say one thing, the clever person understands three.",
		text		: "When you say one thing, the clever person understands three.",
		avatarURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-29-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-29-830x467.jpg",
		media_C 	: false,
	},

	{
		title		: "The temptation to quit will be greatest just before you are about to succeed.",
		text		: "The temptation to quit will be greatest just before you are about to succeed.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-28.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-28.jpg",
		media_C 	: false,
	},
	{
		title		: "Silence is a source of great strength.",
		text		: "Silence is a source of great strength.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-27.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-27.jpg",
		media_C 	: false,
	},
	{
		title		: "If you survived a storm, you won’t be bothered by the rain.",
		text		: "If you survived a storm, you won’t be bothered by the rain.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-26.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-26.jpg",
		media_C 	: false,
	},
	{
		title		: "When anger arises, think of the consequences.",
		text		: "When anger arises, think of the consequences.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-25-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-25-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "The glory is not in never falling, but in rising every time you fall.",
		text		: "The glory is not in never falling, but in rising every time you fall.",
		avatarURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-24-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-24-830x467.jpg",
		media_C 	: false,
	},

	{
		title		: "Do not impose others what yourself do not desire.",
		text		: "Do not impose others what yourself do not desire.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-23-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-23-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Choose a job you love and you will never have to work a day in your life.",
		text		: "Choose a job you love and you will never have to work a day in your life.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-22-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-22-830x467.jpg",
		media_C 	: false,
	},

	{
		title		: "A wise man makes his own decisions. An ignorant man follows public opinion.",
		text		: "A wise man makes his own decisions. An ignorant man follows public opinion.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-21-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-21-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Do not afraid of moving slowly. Be afraid of standing still.",
		text		: "Do not afraid of moving slowly. Be afraid of standing still.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-20-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-20-830x467.jpg",
		media_C 	: false,
	},
		{
		title		: "Tension is who you think you should be. Relaxation is who you are.",
		text		: "Tension is who you think you should be. Relaxation is who you are.",
		avatarURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-19-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-19-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "The best fighter is never angry.",
		text		: "The best fighter is never angry.",
		avatarURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-18-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-18-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Giving your son a skill is better than giving him one thousand pieces of gold.",
		text		: "Giving your son a skill is better than giving him one thousand pieces of gold.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-17-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-17-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "If your mind is strong, all difficult things will become easy. If your mind is weak, all easy things will become difficult.",
		text		: "If your mind is strong, all difficult things will become easy. If your mind is weak, all easy things will become difficult.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-16-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-16-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "A journey of a thousand miles begin with a single step.",
		text		: "A journey of a thousand miles begin with a single step.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-15-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-15-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Tell me and I’ll forget. Show me and I may remember. Involves me and I’ll understand.",
		text		: "Tell me and I’ll forget. Show me and I may remember. Involves me and I’ll understand.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-14-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-14-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "The person who removes a mountain begins by carrying away small stones.",
		text		: "The person who removes a mountain begins by carrying away small stones.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-13.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-13.jpg",
		media_C 	: false,
	},

	{
		title		: "The person who says something is impossible should not interrupt the person who is doing it.",
		text		: "The person who says something is impossible should not interrupt the person who is doing it.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-12.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-12.jpg",
		media_C 	: false,
	},
	{
		title		: "The best time to plant a tree was 20 years ago. The second best time is now.",
		text		: "The best time to plant a tree was 20 years ago. The second best time is now.",
		avatarURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-11.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-11.jpg",
		media_C 	: false,
	},
	{
		title		: "When the winds of change blows, some people build walls and others build windmills.",
		text		: "When the winds of change blows, some people build walls and others build windmills.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-10-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-10-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "He who asks is a fool for 5 minutes, but he who does not ask remains a fool forever.",
		text		: "He who asks is a fool for 5 minutes, but he who does not ask remains a fool forever.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-09-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-09-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Life is really simple, but we insist on making it complicated.",
		text		: "Life is really simple, but we insist on making it complicated.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-08-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-08-830x467.jpg",
		media_C 	: false,
	},

	{
		title		: "A man who chases two rabbits catches neither.",
		text		: "A man who chases two rabbits catches neither.",
		avatarURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-07-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-07-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "He will win who knows when to fight and when not to fight.",
		text		: "He will win who knows when to fight and when not to fight.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-06-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-06-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Don’t fear the enemy that attacks you, but the fake friend that hugs you.",
		text		: "Don’t fear the enemy that attacks you, but the fake friend that hugs you.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-05-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-05-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "He who returns from a journey is not the same as he who left.",
		text		: "He who returns from a journey is not the same as he who left.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-04-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-04-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Opportunities don’t just happen, you create them.",
		text		: "Opportunities don’t just happen, you create them.",
		avatarURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-03-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn2.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-03-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "Failure is not falling down but refusing to get up.",
		text		: "Failure is not falling down but refusing to get up.",
		avatarURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-02-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn3.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-02-830x467.jpg",
		media_C 	: false,
	},
	{
		title		: "You discover who you are by acting naturally.",
		text		: "You discover who you are by acting naturally.",
		avatarURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-01-830x467.jpg",
		avatar_C	: false,
		mediaURL	: "https://cdn4.geckoandfly.com/wp-content/uploads/2015/09/chinese-proverbs-quotes-saying-01-830x467.jpg",
		media_C 	: false,
	},

]