import * as g                           from '../../types/genetics'

export const ABC: g.snapMargin = [] as any;
export const MDL: g.OrganelleType[] = [];
export const DNA: g.gene[] = [
	{
		title		: "PSE_1",
		text 		: '[{"a":[{"type":"Text","value":"Was sind die Legenden der PSE Vorlesung?"}],"b":[{"type":"Image","value":0}]},{"a":[{"type":"Text","value":"Was sind Qualitätseigenschaften für gute Software?"}],"b":[{"type":"Image","value":1}]},{"a":[{"type":"Text","value":"Wieso ist Softwarequalität wichtig?"}],"b":[{"type":"Image","value":2},{"type":"Text","value":"Einen Fehler in 10+ Millionen Zeilen Code zu finden ist fast unmöglich."}]},{"a":[{"type":"Text","value":"Wie ist der allgemeine Aufbau von Computern?"}],"b":[{"type":"Image","value":3},{"type":"Image","value":4}]},{"a":[{"type":"Text","value":"Wie läuft Informations- und Datenverarbeitung im Groben ab?"}],"b":[{"type":"Image","value":5}]},{"a":[{"type":"Text","value":"Was ist die Definition von Software?"}],"b":[{"type":"Image","value":6}]}]',
		avatarURL	: "https://www.pse-stuttgart-ludwigsburg.de/wp-content/uploads/2019/12/panthermedia_B118531450_3508x2339-1024x683.jpg",
		mediaURL	: ""
	},
	{
		title		: "PSE_2",
		text 		: '[{"a":[{"type":"Text","value":"Was unterscheidet Software von Programmen?"}],"b":[{"type":"Text","value":"Zur Software gehören neben dem Programm alle Dinge (Anforderungsbeschreibung, Spezifikationen, Handbücher,...) die für ihre Nutzung, Wartung, etc wichtig sind."},{"type":"Text","value":"Sie ist also mehr als das Programm."}]},{"a":[{"type":"Text","value":"Was ist ein Pseudocode?"}],"b":[{"type":"Text","value":"Ein Pseudocode nutzt nur Teile der Programmiersprache und beschreibt in anderen Teilen was man noch programmieren muss."},{"type":"Text","value":"Beispiel:"},{"type":"Image","value":7}]},{"a":[{"type":"Text","value":"Was sind die Konventionen für Klassennamen in Java?"}],"b":[{"type":"Image","value":8}]},{"a":[{"type":"Text","value":"Welche Elemente verbessern im folgendem Code die Lesbarkeit? Und sind diese für die Programmausführung relevant?"},{"type":"Image","value":9}],"b":[{"type":"Image","value":10}]},{"a":[{"type":"Text","value":"Was ist die fundamentalste Instruktion in objektorientierten Programmiersprachen?"}],"b":[{"type":"Image","value":11}]},{"a":[{"type":"Text","value":"Was sind die Stilregeln für Objektnamen?"}],"b":[{"type":"Text","value":"Kleingeschreibung und Camel Cased"},{"type":"Text","value":"(zum Vergleich Klassennamen sind Groß und Camel Cased)"}]},{"a":[{"type":"Text","value":"Was ist ein Objekt?"}],"b":[{"type":"Image","value":12}]},{"a":[{"type":"Text","value":"Was sind die zentralen Eigenschaften von Objekten?"}],"b":[{"type":"Image","value":13}]},{"a":[{"type":"Text","value":"Was sind Abfragen?"}],"b":[{"type":"Text","value":"Operationen mit dem"},{"type":"Image","value":14}]},{"a":[{"type":"Text","value":"Was sind Kommandos?"}],"b":[{"type":"Text","value":"Operationen mit dem"},{"type":"Image","value":15}]},{"a":[{"type":"Text","value":"Worauf muss man bei Kommandos und Abfragen achten?"}],"b":[{"type":"Text","value":"Keinesfalls beide vermischen:"},{"type":"Image","value":16}]},{"a":[{"type":"Text","value":"Wie lautet die Definition für Objekte?"}],"b":[{"type":"Image","value":17}]},{"a":[{"type":"Text","value":"Wie lautet die Definition und Klassifizierung von Operationen?"}],"b":[{"type":"Image","value":18}]},{"a":[{"type":"Text","value":"Was sind Argumente?"}],"b":[{"type":"Image","value":19},{"type":"Image","value":20}]},{"a":[{"type":"Text","value":"Wieso ist es wichtig für Objekte und Operationen (oder allgemein beim Programmieren) gute Namen zu wählen?"}],"b":[{"type":"Text","value":"wug.fluff()"},{"type":"Text","value":"x.schwurbel()"},{"type":"Text","value":"vs."},{"type":"Text","value":"game.display()"},{"type":"Text","value":"paule.move()"},{"type":"Text","value":"Gute Namen ermöglichen uns und anderen Programme zu lesen und verstehen."}]}]',
		avatarURL	: "https://www.pse-stuttgart-ludwigsburg.de/wp-content/uploads/2019/12/panthermedia_B118531450_3508x2339-1024x683.jpg",
		mediaURL	: ""
	},
	{
		title		: "PSE_3",
		text 		: '[{"a":[{"type":"Text","value":"Was ist eine Programmiersprache?"}],"b":[{"type":"Image","value":22}]},{"a":[{"type":"Text","value":"Was sind Instruktionen? Und welche Stilregel muss man beachten?"}],"b":[{"type":"Image","value":23},{"type":"Image","value":24}]},{"a":[{"type":"Text","value":"Was ist ein Ausdruck?"}],"b":[{"type":"Image","value":25}]},{"a":[{"type":"Text","value":"Was ist Syntax?"}],"b":[{"type":"Image","value":26},{"type":"Image","value":27}]},{"a":[{"type":"Text","value":"Was ist Semantik?"}],"b":[{"type":"Image","value":28},{"type":"Image","value":29}]},{"a":[{"type":"Text","value":"Was ist Pragmatik?"}],"b":[{"type":"Image","value":30},{"type":"Image","value":31}]},{"a":[{"type":"Text","value":"Was ist die Syntax und Semantik eines Programms?"}],"b":[{"type":"Image","value":32}]},{"a":[{"type":"Text","value":"Wie sieht die syntaktische Struktur einer Java Klasse aus?"},{"type":"Image","value":33},{"type":"Text","value":"(welche Elemente sind in diesem Beispiel)"}],"b":[{"type":"Image","value":34}]},{"a":[{"type":"Text","value":"Was sind die Unterschiede zwischen natürlichen Sprachen und ❝künstlichen Programmiersprachen?"},{"type":"Text","value":"Und wie sind Kommentare in diesem Zusammenhand zu verstehen?"}],"b":[{"type":"Image","value":35}]},{"a":[{"type":"Text","value":"Welche Stilregeln gibt es für  Bezeichner?"}],"b":[{"type":"Image","value":36},{"type":"Image","value":37},{"type":"Text","value":"Es empfiehlt sich dabei immer Wörter zu wählen die einen intuitiven und eindeutigen Bezug haben zu den Objekten (Was sie sind oder darstellen) oder Methoden (was sie machen oder abfragen) des Programms."},{"type":"Image","value":38}]},{"a":[{"type":"Text","value":"Wie sieht ein Abstract Syntax Tree AST aus?"},{"type":"Text","value":"z.B. für:"},{"type":"Image","value":39}],"b":[{"type":"Image","value":40}]},{"a":[{"type":"Text","value":"Was sind die grundlegenden Elemente eines Abstrakten Syntaxbaums (AST)?"}],"b":[{"type":"Image","value":41}]},{"a":[{"type":"Text","value":"Was versteht man unter Lexikale?"}],"b":[{"type":"Image","value":42}]}]',
		avatarURL	: "https://www.pse-stuttgart-ludwigsburg.de/wp-content/uploads/2019/12/panthermedia_B118531450_3508x2339-1024x683.jpg",
		mediaURL	: ""
	},
	{
		title		: "PSE_4",
		text 		: '[{"a":[{"type":"Text","value":"Was ist eine Schnittstelle? Was ist ein Kunde? Was ist ein Anbieter?"}],"b":[{"type":"Image","value":44},{"type":"Image","value":45}]},{"a":[{"type":"Text","value":"Was ist Javadoc? Wieso ist die Dokumentation von Programmen wichtig?"}],"b":[{"type":"Image","value":46},{"type":"Image","value":47}]},{"a":[{"type":"Text","value":"Wie schreibt man Javadoc Kommentare? Was sind die Stilregeln für diese?"}],"b":[{"type":"Image","value":48},{"type":"Image","value":49},{"type":"Image","value":50},{"type":"Image","value":51}]},{"a":[{"type":"Text","value":"Welche Javadoc-Tags kennst du?"}],"b":[{"type":"Image","value":52}]},{"a":[{"type":"Text","value":"Was ist eine Klasse?"}],"b":[{"type":"Image","value":53}]},{"a":[{"type":"Text","value":"Was ist eine Instanz? Was ist eine generierende Klasse?"}],"b":[{"type":"Image","value":54}]},{"a":[{"type":"Text","value":"Wo ❝existieren❝ Klassen und Objekte?"}],"b":[{"type":"Image","value":55}]},{"a":[{"type":"Text","value":"Was ist ein Typ? Was ist die Beziehung zu Ausdrücken und Objekten?"}],"b":[{"type":"Image","value":56}]},{"a":[{"type":"Text","value":"Was ist die Verwendung von Paketen in Java? Was sind Stilregeln für Pakete?"}],"b":[{"type":"Text","value":"Java verwendet Pakete als Namensräume."},{"type":"Image","value":57},{"type":"Text","value":"Beispiel:"},{"type":"Image","value":58},{"type":"Image","value":59},{"type":"Image","value":60}]},{"a":[{"type":"Text","value":"Was ist ein Vertrag? Welche Vertragsarten gibt es?"}],"b":[{"type":"Image","value":61},{"type":"Image","value":62}]},{"a":[{"type":"Text","value":"Was ist eine Vorbedingung? Wie geht man beim Schreiben von Vorbedingungen vor?"}],"b":[{"type":"Image","value":63},{"type":"Image","value":64}]},{"a":[{"type":"Text","value":"Was ist JML? Wofür brauchen wir es?"}],"b":[{"type":"Image","value":65}]},{"a":[{"type":"Text","value":"Was ist eine Nachbedingung? Wie geht man beim Schreiben von Nachbedingungen vor?"}],"b":[{"type":"Image","value":66},{"type":"Image","value":67}]},{"a":[{"type":"Text","value":"Was ist das Vorbedingungsprinzip? Was ist das Nachbedingungsprinzip?"}],"b":[{"type":"Text","value":"Eine Software die eines der Prinzipien verletzt ist fehlerhaft."},{"type":"Image","value":68},{"type":"Image","value":69}]},{"a":[{"type":"Text","value":"Was ist eine Klasseninvariante?"}],"b":[{"type":"Image","value":70}]}]',
		avatarURL	: "https://www.pse-stuttgart-ludwigsburg.de/wp-content/uploads/2019/12/panthermedia_B118531450_3508x2339-1024x683.jpg",
		mediaURL	: ""
	},
	{
		title		: "PSE_5",
		text 		: '[{"a":[{"type":"Text","value":"Wie definiert man einen Booleschen Ausdruck?"}],"b":[{"type":"Image","value":72},{"type":"Image","value":73}]},{"a":[{"type":"Text","value":"Gib die Wahrheitstabelle für die Verneinung an."}],"b":[{"type":"Image","value":74}]},{"a":[{"type":"Text","value":"Gib die Eigenschaften und Wahrheitstabelle der Disjunktion an."}],"b":[{"type":"Image","value":75}]},{"a":[{"type":"Text","value":"Gib die Wahrheitstabelle und Eigenschaften der Konjunktion an."}],"b":[{"type":"Image","value":76}]},{"a":[{"type":"Text","value":"Was ist eine Wahrheitsbelegung?"}],"b":[{"type":"Image","value":77}]},{"a":[{"type":"Text","value":"Wie groß ist eine Wahrheitstablle für m Teilausdrücke und n Variablen?"}],"b":[{"type":"Image","value":78}]},{"a":[{"type":"Text","value":"Was ist eine Tautologie?"}],"b":[{"type":"Image","value":79}]},{"a":[{"type":"Text","value":"Was ist ein Widerspruch?"}],"b":[{"type":"Image","value":80}]},{"a":[{"type":"Text","value":"Wann ist ein Ausdruck erfüllbar?"}],"b":[{"type":"Image","value":81}]},{"a":[{"type":"Text","value":"Gib die Wahrheitstabelle und Eigenschaften für die Gleichheit an."}],"b":[{"type":"Image","value":82}]},{"a":[{"type":"Text","value":"Gib die De Morganschen Gesetze an."}],"b":[{"type":"Image","value":83}]},{"a":[{"type":"Text","value":"Was sind die Stilregeln für boolesche Ausdrücke?"}],"b":[{"type":"Image","value":84}]},{"a":[{"type":"Text","value":"Gib die Wahrheitstabelle und Eigenschaften für die Implikation an."}],"b":[{"type":"Image","value":85}]},{"a":[{"type":"Text","value":"Was sind semistrikte Operatoren?"}],"b":[{"type":"Image","value":86}]},{"a":[{"type":"Text","value":"Wann verwendet man gewöhnliche und wann semistrikte Operatoren?"}],"b":[{"type":"Image","value":87}]},{"a":[{"type":"Text","value":"Wie sind die verschiedenen Notationen der booleschen Operationen (Java, Mathematik, JML)?"}],"b":[{"type":"Image","value":88}]},{"a":[{"type":"Text","value":"Wie ist der Existenzquantor definiert?"}],"b":[{"type":"Image","value":89}]},{"a":[{"type":"Text","value":"Wie ist der Allquantor definiert?"}],"b":[{"type":"Image","value":90}]},{"a":[{"type":"Text","value":"Wann ist eine Existenzaussage wahr/falsch?"}],"b":[{"type":"Image","value":91}]}]',
		avatarURL	: "https://www.pse-stuttgart-ludwigsburg.de/wp-content/uploads/2019/12/panthermedia_B118531450_3508x2339-1024x683.jpg",
		mediaURL	: ""
	},
	{
		title		: "PSE_6",
		text 		: '[{"a":[{"type":"Text","value":"Was sind die UML Notationen für Allquantor und Existenzquantor?"}],"b":[{"type":"Text","value":"Allquantor:"},{"type":"Text","value":"forall"},{"type":"Text","value":"Existenzquantor:"},{"type":"Text","value":"exists"}]},{"a":[{"type":"Text","value":"Was ist ein Bezeichner, eine Entität, eine Variable, eine Objektvariable?"}],"b":[{"type":"Image","value":93}]},{"a":[{"type":"Text","value":"Wie wird eine Entität an ein Objekt gebunden?"}],"b":[{"type":"Image","value":94},{"type":"Image","value":95}]},{"a":[{"type":"Text","value":"Wie speichert Java Objektvariablen?"}],"b":[{"type":"Image","value":96}]},{"a":[{"type":"Text","value":"Was ist der initiale Zustand einer Objektreferenz in Java?"}],"b":[{"type":"Image","value":97}]},{"a":[{"type":"Text","value":"Was sind die möglichen Zustände einer Referenz? Wie kann man auf diese testen?"}],"b":[{"type":"Image","value":98}]},{"a":[{"type":"Text","value":"Was passiert bei Funktionsaufrufen auf ungebundene Objekte? Wie behandelt Java diese?"}],"b":[{"type":"Image","value":99},{"type":"Image","value":100}]},{"a":[{"type":"Text","value":"Welche Stilregel gibt es bei der Nutzung von Objektreferenzen?"}],"b":[{"type":"Image","value":101}]},{"a":[{"type":"Text","value":"Wie wird in Java das aktuelle Objekt referenziert? Was simd die Eigenschaften der Referenz?"}],"b":[{"type":"Image","value":102},{"type":"Image","value":103}]},{"a":[{"type":"Text","value":"Wie läuft der Prozess der Objekterzeugung ab?"}],"b":[{"type":"Image","value":104}]},{"a":[{"type":"Text","value":"Wie wird ein Hamster-Objekt erzeugt?"}],"b":[{"type":"Image","value":105}]},{"a":[{"type":"Text","value":"Was sind Erzeugungsprozeduren (Konstruktoren)? Wozu brauchen wir diese?"}],"b":[{"type":"Image","value":106},{"type":"Image","value":107},{"type":"Image","value":108}]},{"a":[{"type":"Text","value":"Was besagt das Prinzip der Erzeugung?"}],"b":[{"type":"Image","value":109}]}]',
		avatarURL	: "https://www.pse-stuttgart-ludwigsburg.de/wp-content/uploads/2019/12/panthermedia_B118531450_3508x2339-1024x683.jpg",
		mediaURL	: ""
	},
	{
		title		: "PSE_7",
		text 		: '[{"a":[{"type":"Text","value":"Was ist ein Algorithmus? Welche 5 Eigenschaften hat er?"}],"b":[{"type":"Image","value":112},{"type":"Image","value":113}]},{"a":[{"type":"Text","value":"Was ist der Unterschied zwischen Algorithmus und Programm?"}],"b":[{"type":"Image","value":114}]},{"a":[{"type":"Text","value":"Was sind Kontrollflussstrukturen? Gib Beispiele."}],"b":[{"type":"Image","value":115}]},{"a":[{"type":"Text","value":"Was ist die Problemlösungstechnik einer Sequenz?"}],"b":[{"type":"Image","value":116}]},{"a":[{"type":"Text","value":"Was ist die Problemlösungstechnik einer Verzweigung?"}],"b":[{"type":"Image","value":117}]},{"a":[{"type":"Text","value":"Was ist die Problemlösungstechnik einer Schleife?"}],"b":[{"type":"Image","value":118}]},{"a":[{"type":"Text","value":"Wie ist die Korrektheit einer Sequenz garantiert?"}],"b":[{"type":"Image","value":119}]},{"a":[{"type":"Text","value":"Was sind Stilregeln für Sequenzen?"}],"b":[{"type":"Image","value":120}]}]',
		avatarURL	: "https://www.pse-stuttgart-ludwigsburg.de/wp-content/uploads/2019/12/panthermedia_B118531450_3508x2339-1024x683.jpg",
		mediaURL	: ""
	}

]